#!/usr/bin/env python3
"""Deep cleanup: translate remaining French words/phrases in EN pages.
Targets text inside HTML tags, meta content, title, schema.org, etc.
Careful not to touch URLs, CSS classes, or HTML attributes."""
import os, re

EN_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "en")

# Word-level translations (applied carefully, case-sensitive)
WORD_FIXES = [
    # ---- TITLES & META (high priority, full phrases) ----
    ("Dominez Google", "Dominate Google"),
    ("Agence SEO", "SEO Agency"),
    ("Agence digitale", "Digital agency"),
    ("Agence Digital", "Digital Agency"),
    ("Agence de ", "Agency for "),
    ("Agence premium", "Premium agency"),
    ("agence premium", "premium agency"),
    ("votre agence", "your agency"),
    ("notre agence", "our agency"),
    ("une agence", "an agency"),
    ("Agence ", "Agency "),
    ("agence ", "agency "),

    # Spécialisée
    ("spécialisée en", "specialized in"),
    ("sp&eacute;cialis&eacute;e en", "specialized in"),
    ("spécialisé en", "specialized in"),
    ("sp&eacute;cialis&eacute; en", "specialized in"),
    ("spécialisée", "specialized"),
    ("sp&eacute;cialis&eacute;e", "specialized"),

    # Stratégie
    ("stratégie sur mesure", "custom strategy"),
    ("strat&eacute;gie sur mesure", "custom strategy"),
    ("stratégie adaptée", "tailored strategy"),
    ("strat&eacute;gie adapt&eacute;e", "tailored strategy"),
    ("stratégie personnalisée", "personalized strategy"),
    ("strat&eacute;gie personnalis&eacute;e", "personalized strategy"),
    ("stratégie digitale", "digital strategy"),
    ("strat&eacute;gie digitale", "digital strategy"),
    ("Stratégie", "Strategy"),
    ("Strat&eacute;gie", "Strategy"),
    ("stratégie", "strategy"),
    ("strat&eacute;gie", "strategy"),
    ("stratégique", "strategic"),
    ("strat&eacute;gique", "strategic"),

    # Résultats
    ("résultats mesurables", "measurable results"),
    ("r&eacute;sultats mesurables", "measurable results"),
    ("résultats concrets", "concrete results"),
    ("r&eacute;sultats concrets", "concrete results"),
    ("résultats prouvés", "proven results"),
    ("r&eacute;sultats prouv&eacute;s", "proven results"),
    ("résultats", "results"),
    ("r&eacute;sultats", "results"),
    ("résultat", "result"),
    ("r&eacute;sultat", "result"),

    # Référencement
    ("Référencement naturel", "Organic search"),
    ("R&eacute;f&eacute;rencement naturel", "Organic search"),
    ("Référencement Naturel", "Organic Search"),
    ("R&eacute;f&eacute;rencement Naturel", "Organic Search"),
    ("RÉFÉRENCEMENT NATUREL", "ORGANIC SEARCH"),
    ("référencement naturel", "organic search"),
    ("r&eacute;f&eacute;rencement naturel", "organic search"),
    ("Référencement", "SEO"),
    ("R&eacute;f&eacute;rencement", "SEO"),
    ("référencement", "SEO"),
    ("r&eacute;f&eacute;rencement", "SEO"),

    # Visibilité
    ("visibilité en ligne", "online visibility"),
    ("visibilit&eacute; en ligne", "online visibility"),
    ("visibilité", "visibility"),
    ("visibilit&eacute;", "visibility"),

    # Common verbs/phrases in descriptions
    ("Nous vous amenons en", "We get you to the"),
    ("Nous vous aidons à", "We help you"),
    ("Nous vous aidons &agrave;", "We help you"),
    ("nous vous aidons à", "we help you"),
    ("nous vous aidons &agrave;", "we help you"),
    ("Nous créons", "We create"),
    ("Nous cr&eacute;ons", "We create"),
    ("nous créons", "we create"),
    ("Nous développons", "We develop"),
    ("Nous d&eacute;veloppons", "We develop"),
    ("Nous optimisons", "We optimize"),
    ("nous optimisons", "we optimize"),
    ("Nous analysons", "We analyze"),
    ("Nous transformons", "We transform"),
    ("Vous méritez", "You deserve"),
    ("Vous m&eacute;ritez", "You deserve"),
    ("vous méritez", "you deserve"),
    ("d'être trouvé", "to be found"),
    ("d&#39;&ecirc;tre trouv&eacute;", "to be found"),
    ("d'être trouve", "to be found"),

    # Prepositions/articles in context
    ("votre site", "your website"),
    ("votre entreprise", "your business"),
    ("votre marché", "your market"),
    ("votre march&eacute;", "your market"),
    ("votre projet", "your project"),
    ("votre croissance", "your growth"),
    ("votre présence", "your presence"),
    ("votre pr&eacute;sence", "your presence"),
    ("votre succès", "your success"),
    ("votre succ&egrave;s", "your success"),
    ("votre réussite", "your success"),
    ("votre r&eacute;ussite", "your success"),
    ("votre stratégie", "your strategy"),
    ("votre strat&eacute;gie", "your strategy"),
    ("votre visibilité", "your visibility"),
    ("votre visibilit&eacute;", "your visibility"),
    ("Votre site", "Your website"),
    ("Votre entreprise", "Your business"),
    ("Votre marché", "Your market"),
    ("Votre march&eacute;", "Your market"),
    ("Votre projet", "Your project"),
    ("Votre croissance", "Your growth"),
    ("Votre présence", "Your presence"),
    ("Votre pr&eacute;sence", "Your presence"),
    ("Votre réussite", "Your success"),
    ("Votre r&eacute;ussite", "Your success"),

    # Notre/nos
    ("notre équipe", "our team"),
    ("notre &eacute;quipe", "our team"),
    ("Notre équipe", "Our team"),
    ("Notre &eacute;quipe", "Our team"),
    ("notre expertise", "our expertise"),
    ("Notre expertise", "Our expertise"),
    ("notre approche", "our approach"),
    ("Notre approche", "Our approach"),
    ("notre méthode", "our method"),
    ("notre m&eacute;thode", "our method"),
    ("nos clients", "our clients"),
    ("Nos clients", "Our clients"),
    ("nos services", "our services"),
    ("Nos services", "Our services"),
    ("nos experts", "our experts"),
    ("Nos experts", "Our experts"),

    # Common adjectives
    ("sur mesure", "custom"),
    ("clé en main", "turnkey"),
    ("cl&eacute; en main", "turnkey"),
    ("clés en main", "turnkey"),
    ("cl&eacute;s en main", "turnkey"),
    ("mots-clés", "keywords"),
    ("mots-cl&eacute;s", "keywords"),
    ("mots clés", "keywords"),
    ("mots cl&eacute;s", "keywords"),
    ("haut de gamme", "high-end"),
    ("en ligne", "online"),
    ("gratuit", "free"),
    ("premium", "premium"),

    # Common nouns
    ("trafic organique", "organic traffic"),
    ("trafic qualifié", "qualified traffic"),
    ("trafic qualifi&eacute;", "qualified traffic"),
    ("trafic", "traffic"),
    ("moteurs de recherche", "search engines"),
    ("première page", "first page"),
    ("premi&egrave;re page", "first page"),
    ("Première page", "First page"),
    ("Premi&egrave;re page", "First page"),
    ("page de résultats", "results page"),
    ("page de r&eacute;sultats", "results page"),
    ("chiffre d'affaires", "revenue"),
    ("chiffre d&#39;affaires", "revenue"),
    ("retour sur investissement", "return on investment"),
    ("taux de conversion", "conversion rate"),
    ("expérience utilisateur", "user experience"),
    ("exp&eacute;rience utilisateur", "user experience"),
    ("expérience", "experience"),
    ("exp&eacute;rience", "experience"),
    ("croissance", "growth"),
    ("performance", "performance"),
    ("performances", "performance"),

    # Publicité
    ("Publicité payante", "Paid advertising"),
    ("Publicit&eacute; payante", "Paid advertising"),
    ("publicité payante", "paid advertising"),
    ("publicit&eacute; payante", "paid advertising"),
    ("Publicité", "Advertising"),
    ("Publicit&eacute;", "Advertising"),
    ("publicité", "advertising"),
    ("publicit&eacute;", "advertising"),

    # Rédaction
    ("Rédaction de contenu", "Content writing"),
    ("R&eacute;daction de contenu", "Content writing"),
    ("Rédaction SEO", "SEO writing"),
    ("R&eacute;daction SEO", "SEO writing"),
    ("Rédaction", "Writing"),
    ("R&eacute;daction", "Writing"),
    ("rédaction", "writing"),
    ("r&eacute;daction", "writing"),

    # Création
    ("Création de sites web", "Website creation"),
    ("Cr&eacute;ation de sites web", "Website creation"),
    ("Création de Sites Web", "Website Creation"),
    ("Cr&eacute;ation de Sites Web", "Website Creation"),
    ("Création de site web", "Website creation"),
    ("Cr&eacute;ation de site web", "Website creation"),
    ("Création de site", "Website creation"),
    ("Cr&eacute;ation de site", "Website creation"),
    ("Création", "Creation"),
    ("Cr&eacute;ation", "Creation"),
    ("création", "creation"),
    ("cr&eacute;ation", "creation"),

    # Automatisation
    ("Automatisation", "Automation"),
    ("automatisation", "automation"),

    # Design
    ("Identité visuelle", "Visual identity"),
    ("Identit&eacute; visuelle", "Visual identity"),
    ("identité visuelle", "visual identity"),
    ("identit&eacute; visuelle", "visual identity"),
    ("Charte graphique", "Brand guidelines"),
    ("charte graphique", "brand guidelines"),

    # Consulting
    ("Consulting Digital", "Digital Consulting"),
    ("consulting digital", "digital consulting"),

    # More verbs
    ("Développer", "Develop"),
    ("D&eacute;velopper", "Develop"),
    ("développer", "develop"),
    ("d&eacute;velopper", "develop"),
    ("Optimiser", "Optimize"),
    ("optimiser", "optimize"),
    ("Améliorer", "Improve"),
    ("Am&eacute;liorer", "Improve"),
    ("améliorer", "improve"),
    ("am&eacute;liorer", "improve"),
    ("Transformer", "Transform"),
    ("transformer", "transform"),
    ("Augmenter", "Increase"),
    ("augmenter", "increase"),
    ("Maximiser", "Maximize"),
    ("maximiser", "maximize"),
    ("Booster", "Boost"),
    ("booster", "boost"),
    ("Générer", "Generate"),
    ("G&eacute;n&eacute;rer", "Generate"),
    ("générer", "generate"),
    ("g&eacute;n&eacute;rer", "generate"),
    ("Mesurer", "Measure"),
    ("mesurer", "measure"),
    ("Convertir", "Convert"),
    ("convertir", "convert"),

    # City/location phrases
    ("la capitale française", "the French capital"),
    ("la capitale fran&ccedil;aise", "the French capital"),
    ("le marché local", "the local market"),
    ("le march&eacute; local", "the local market"),
    ("marché local", "local market"),
    ("march&eacute; local", "local market"),

    # More meta/title patterns
    ("Pirabel Labs —", "Pirabel Labs —"),
    ("Solutions digitales", "Digital solutions"),
    ("solutions digitales", "digital solutions"),
    ("services digitaux", "digital services"),
    ("Services digitaux", "Digital services"),
    ("marketing digital", "digital marketing"),
    ("Marketing Digital", "Digital Marketing"),
    ("Marketing digital", "Digital marketing"),
    ("transformation digitale", "digital transformation"),
    ("Transformation digitale", "Digital transformation"),
    ("présence digitale", "digital presence"),
    ("pr&eacute;sence digitale", "digital presence"),
    ("Présence digitale", "Digital presence"),
    ("Pr&eacute;sence digitale", "Digital presence"),

    # Connectors and common phrases
    ("et de", "and"),
    ("grâce à", "thanks to"),
    ("gr&acirc;ce &agrave;", "thanks to"),
    ("grâce au", "thanks to"),
    ("afin de", "in order to"),
    ("dans le but de", "with the aim of"),
    ("au sein de", "within"),
    ("à travers", "through"),
    ("&agrave; travers", "through"),
    ("qui vous permet", "that allows you"),
    ("qui vous aide", "that helps you"),
    ("adaptée à", "adapted to"),
    ("adapt&eacute;e &agrave;", "adapted to"),
    ("adapté à", "adapted to"),
    ("adapt&eacute; &agrave;", "adapted to"),
    ("conçue pour", "designed for"),
    ("con&ccedil;ue pour", "designed for"),
    ("conçu pour", "designed for"),
    ("con&ccedil;u pour", "designed for"),
    ("pensé pour", "designed for"),
    ("pens&eacute; pour", "designed for"),
    ("optimisé pour", "optimized for"),
    ("optimis&eacute; pour", "optimized for"),
    ("dédié à", "dedicated to"),
    ("d&eacute;di&eacute; &agrave;", "dedicated to"),
    ("dédiée à", "dedicated to"),
    ("d&eacute;di&eacute;e &agrave;", "dedicated to"),
    ("dédié", "dedicated"),
    ("d&eacute;di&eacute;", "dedicated"),

    # More nouns
    ("entreprise", "business"),
    ("entreprises", "businesses"),
    ("secteur d'activité", "industry"),
    ("secteur d&#39;activit&eacute;", "industry"),
    ("secteur", "sector"),
    ("concurrence", "competition"),
    ("concurrents", "competitors"),
    ("prospect", "prospect"),
    ("prospects", "prospects"),
    ("clients potentiels", "potential clients"),
    ("audience cible", "target audience"),
    ("accompagnement", "support"),
    ("fidélisation", "retention"),
    ("fid&eacute;lisation", "retention"),
    ("acquisition", "acquisition"),
    ("notoriété", "brand awareness"),
    ("notori&eacute;t&eacute;", "brand awareness"),

    # Schema.org / structured data
    ("Agence digitale premium à ", "Premium digital agency in "),
    ("Agence digitale premium a ", "Premium digital agency in "),

    # FAQ answers
    ("Les premiers gains techniques sont visibles sous 30 jours", "First technical gains are visible within 30 days"),
    ("Pour un positionnement solide en première page", "For a solid first page ranking"),
    ("Pour un positionnement solide en premi&egrave;re page", "For a solid first page ranking"),
    ("selon la concurrence de votre secteur", "depending on competition in your sector"),
    ("Google Ads vous apporte du trafic tant que vous payez", "Google Ads brings you traffic as long as you pay"),
    ("Le SEO construit un actif durable", "SEO builds a lasting asset"),
    ("une fois bien positionné", "once well ranked"),
    ("une fois bien positionn&eacute;", "once well ranked"),
    ("votre site attire du trafic gratuitement", "your site attracts traffic for free"),
    ("pendant des mois voire des années", "for months or even years"),
    ("pendant des mois voire des ann&eacute;es", "for months or even years"),
    ("Le SEO offre le meilleur retour sur investissement", "SEO offers the best return on investment"),
    ("de tous les canaux marketing digitaux", "of all digital marketing channels"),
    ("Un euro investi en SEO rapporte en moyenne", "One euro invested in SEO returns on average"),
    ("euros de chiffre d'affaires sur 12 mois", "euros in revenue over 12 months"),
    ("euros de chiffre d&#39;affaires sur 12 mois", "euros in revenue over 12 months"),
    ("Si votre site n'apparaît pas en première page", "If your site doesn't appear on the first page"),
    ("Si votre site n&#39;appara&icirc;t pas en premi&egrave;re page", "If your site doesn't appear on the first page"),
    ("quand vous cherchez vos services", "when you search for your services"),
    ("vous perdez des clients", "you're losing clients"),
    ("Notre audit gratuit vous montre exactement où vous en êtes", "Our free audit shows you exactly where you stand"),
    ("Notre audit gratuit vous montre exactement o&ugrave; vous en &ecirc;tes", "Our free audit shows you exactly where you stand"),
    ("une analyse de votre visibilité actuelle", "an analysis of your current visibility"),
    ("une analyse de votre visibilit&eacute; actuelle", "an analysis of your current visibility"),
    ("un diagnostic technique", "a technical diagnostic"),
    ("une étude de vos concurrents", "a competitor study"),
    ("une &eacute;tude de vos concurrents", "a competitor study"),
    ("des recommandations concrètes", "concrete recommendations"),
    ("des recommandations concr&egrave;tes", "concrete recommendations"),
    ("avec un plan d'action prioritaire", "with a priority action plan"),
    ("avec un plan d&#39;action prioritaire", "with a priority action plan"),
    ("Oui. Startups, PME et grandes entreprises", "Yes. Startups, SMBs and large enterprises"),
    ("Nous adaptons notre stratégie à votre budget", "We adapt our strategy to your budget"),
    ("Nous adaptons notre strat&eacute;gie &agrave; votre budget", "We adapt our strategy to your budget"),
    ("votre marché et vos objectifs spécifiques", "your market and your specific goals"),
    ("votre march&eacute; et vos objectifs sp&eacute;cifiques", "your market and your specific goals"),

    # More patterns found
    ("Naturel", "Search"),
    ("clés", "keys"),
    ("cl&eacute;s", "keys"),
    ("précis", "precise"),
    ("pr&eacute;cis", "precise"),
    ("qualifié", "qualified"),
    ("qualifi&eacute;", "qualified"),
    ("qualité", "quality"),
    ("qualit&eacute;", "quality"),
    ("optimisé", "optimized"),
    ("optimis&eacute;", "optimized"),
    ("réduit", "reduced"),
    ("r&eacute;duit", "reduced"),
    ("méthode", "method"),
    ("m&eacute;thode", "method"),
    ("apparaît", "appears"),
    ("appara&icirc;t", "appears"),
    ("même", "same"),
    ("m&ecirc;me", "same"),
    ("être", "be"),
    ("&ecirc;tre", "be"),
    ("êtes", "are"),
    ("&ecirc;tes", "are"),
    ("où", "where"),
    ("o&ugrave;", "where"),
    ("là", "there"),
    ("l&agrave;", "there"),
]

count = 0
for root, dirs, files in os.walk(EN_DIR):
    for f in files:
        if not f.endswith('.html'):
            continue
        path = os.path.join(root, f)
        with open(path, 'r', encoding='utf-8', errors='replace') as fh:
            content = fh.read()
        original = content
        for fr, en in WORD_FIXES:
            content = content.replace(fr, en)
        if content != original:
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(content)
            count += 1

print(f"Deep fix applied to {count} EN files")
