services:
  - type: web
    name: pirabel-api
    runtime: node
    rootDir: app
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: ADMIN_SECRET_PATH
        value: pirabel-admin-7x9k2m
      - key: CLIENT_SECRET_PATH
        value: espace-client-4p8w1n
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_EMAIL
        value: contact@pirabellabs.com
      - key: FROM_EMAIL
        value: contact@pirabellabs.com
      - key: SITE_URL
        value: https://pirabel-labs.vercel.app
