#!/usr/bin/env python3
"""
Translate Pirabel Labs FR -> EN.
Faithful 1:1 copy — only visible text is translated.
"""
import os, re

SRC = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(SRC, "en")

# Long phrases first to avoid partial matches
T = [
    # === HTML ATTRIBUTES ===
    ('html lang="fr"', 'html lang="en"'),
    ('og:locale" content="fr_FR"', 'og:locale" content="en_US"'),
    ('hreflang="fr"', 'hreflang="en"'),
    ('hreflang="x-default"', 'hreflang="en"'),

    # === NAV (exact match with > and </a>) ===
    (">L'AGENCE</a>", ">THE AGENCY</a>"),
    (">ACCUEIL</a>", ">HOME</a>"),
    (">RÉSULTATS</a>", ">RESULTS</a>"),
    (">R&Eacute;SULTATS</a>", ">RESULTS</a>"),
    (">À PROPOS</a>", ">ABOUT</a>"),
    (">CARRIÈRES</a>", ">CAREERS</a>"),
    (">Accueil</a>", ">Home</a>"),
    (">Résultats</a>", ">Results</a>"),
    (">À propos</a>", ">About</a>"),
    (">Carrières</a>", ">Careers</a>"),
    (">Contact</a>", ">Contact</a>"),
    ("> Mon Espace</a>", "> My Account</a>"),
    (">Mon Espace</a>", ">My Account</a>"),
    (">Audit Gratuit</a>", ">Free Audit</a>"),

    # === FOOTER ===
    ("L'agence digitale premium au service de votre croissance. Nous construisons les standards de demain pour les entreprises les plus ambitieuses.",
     "The premium digital agency at the service of your growth. We build tomorrow's standards for the most ambitious businesses."),
    ("L'agence digitale next-g&eacute;n&eacute;ration. Partner in Growth. 10 march&eacute;s internationaux, 150+ projets livr&eacute;s.",
     "The next-generation digital agency. Partner in Growth. 10 international markets, 150+ projects delivered."),
    ("L'agence digitale next-génération. Partner in Growth. 10 marchés internationaux, 150+ projets livrés.",
     "The next-generation digital agency. Partner in Growth. 10 international markets, 150+ projects delivered."),
    ("L'agence digitale premium au service de votre croissance.",
     "The premium digital agency serving your growth."),
    ("Agence digitale premium.", "Premium digital agency."),
    (">Services</div>", ">Services</div>"),
    (">Ressources</div>", ">Resources</div>"),
    (">Villes</div>", ">Cities</div>"),
    ("SEO &amp; R&eacute;f&eacute;rencement", "SEO &amp; Organic Search"),
    ("SEO & Référencement", "SEO & Organic Search"),
    ("Création de Sites", "Website Creation"),
    ("Cr&eacute;ation de Sites", "Website Creation"),
    ("IA & Automatisation", "AI & Automation"),
    ("IA &amp; Automatisation", "AI &amp; Automation"),
    ("Publicité Payante", "Paid Advertising"),
    ("Publicit&eacute; Payante", "Paid Advertising"),
    ("Design &amp; Branding", "Design &amp; Branding"),
    ("Vid&eacute;o &amp; Motion", "Video &amp; Motion"),
    ("Video & Motion", "Video & Motion"),
    ("Email &amp; CRM", "Email &amp; CRM"),
    ("Email & CRM", "Email & CRM"),
    (">Etudes de cas</a>", ">Case Studies</a>"),
    (">&Eacute;tudes de cas</a>", ">Case Studies</a>"),
    (">Études de cas</a>", ">Case Studies</a>"),
    ("Tous droits r&eacute;serv&eacute;s", "All rights reserved"),
    ("Tous droits réservés", "All rights reserved"),
    ("Mentions l&eacute;gales", "Legal Notice"),
    ("Mentions légales", "Legal Notice"),
    ("Confidentialit&eacute;", "Privacy Policy"),
    ("Confidentialité", "Privacy Policy"),
    ("Politique de confidentialit&eacute;", "Privacy Policy"),
    ("Politique de confidentialité", "Privacy Policy"),

    # === NEWSLETTER ===
    ("Restez inform&eacute;", "Stay Informed"),
    ("Restez informé", "Stay Informed"),
    ("Recevez nos guides, conseils et actualit&eacute;s directement dans votre bo&icirc;te mail. Pas de spam, que de la valeur.",
     "Receive our guides, tips and news directly in your inbox. No spam, only value."),
    ("Recevez nos guides, conseils et actualités directement dans votre boîte mail. Pas de spam, que de la valeur.",
     "Receive our guides, tips and news directly in your inbox. No spam, only value."),
    ("Recevez nos guides, conseils et actualit&eacute;s directement dans votre bo&icirc;te mail.",
     "Receive our guides, tips and news directly in your inbox."),
    ("Recevez nos articles directement dans votre bo&icirc;te mail.",
     "Receive our articles directly in your inbox."),
    ("Recevez nos articles directement dans votre boîte mail.",
     "Receive our articles directly in your inbox."),
    ('placeholder="Votre email"', 'placeholder="Your email"'),
    (">S'inscrire</", ">Subscribe</"),
    (">S&#39;inscrire</", ">Subscribe</"),
    ("&check; Inscription r&eacute;ussie !", "&check; Successfully subscribed!"),
    ("Inscription r&eacute;ussie !", "Successfully subscribed!"),
    ("Inscription réussie !", "Successfully subscribed!"),

    # === INDEX.HTML HERO ===
    (">Agence Marketing Digital Premium</span>", ">Premium Digital Marketing Agency</span>"),
    ("<span>L'AGENCE</span>", "<span>THE DIGITAL</span>"),
    ("<span>DIGITALE</span>", "<span>AGENCY</span>"),
    ("<span>QUI</span>", "<span>THAT</span>"),
    ("<span>PROPULSE</span>", "<span>PROPELS</span>"),
    ("<span>VOTRE</span>", "<span>YOUR</span>"),
    ('<span style="color:var(--on-surface);">CROISSANCE.</span>', '<span style="color:var(--on-surface);">GROWTH.</span>'),
    ("SEO, cr&eacute;ation de sites web, automatisation IA, publicit&eacute; digitale, branding — nous accompagnons les entreprises ambitieuses avec des solutions sur mesure qui g&eacute;n&egrave;rent des r&eacute;sultats concrets et mesurables. De Paris &agrave; Cotonou, de Casablanca &agrave; Montr&eacute;al.",
     "SEO, website creation, AI automation, digital advertising, branding — we support ambitious businesses with tailored solutions that generate concrete, measurable results. From Paris to Cotonou, from Casablanca to Montreal."),
    (">DOMINER LE MARCHE ", ">DOMINATE THE MARKET "),
    (">DECOUVRIR NOS SERVICES</a>", ">DISCOVER OUR SERVICES</a>"),

    # === PAIN POINTS ===
    ("POURQUOI VOTRE BUSINESS ", "WHY IS YOUR BUSINESS "),
    (">STAGNE ?</span>", ">STAGNATING?</span>"),
    (">Votre site est invisible</h3>", ">Your website is invisible</h3>"),
    ("Vos concurrents apparaissent en premier sur Google et vous perdez des clients chaque jour. Votre site existe, mais personne ne le trouve quand il cherche vos services.",
     "Your competitors appear first on Google and you lose customers every day. Your website exists, but no one finds it when searching for your services."),
    (">Votre trafic ne bouge plus</h3>", ">Your traffic isn't growing</h3>"),
    ("Vous avez investi dans un beau site, mais les visiteurs ne viennent pas. Le compteur de visites reste désespérément plat malgre vos efforts.",
     "You invested in a beautiful website, but visitors aren't coming. The visit counter remains desperately flat despite your efforts."),
    (">Vous brulez du budget pub</h3>", ">You're burning your ad budget</h3>"),
    ("Chaque mois, vous remettez de l'argent dans Google Ads pour avoir des clients. Sans budget pub, plus rien ne rentre. Vous etes pris en otage.",
     "Every month, you pour money into Google Ads to get customers. Without ad budget, nothing comes in. You're being held hostage."),
    (">Votre ancienne agence a échoué</h3>", ">Your former agency failed</h3>"),
    ("Vous avez deja paye une agence. 6 mois plus tard : aucun resultat concret, des rapports incomprehensibles, et une confiance brisee.",
     "You already paid an agency. 6 months later: no concrete results, incomprehensible reports, and broken trust."),
    (">Vous perdez du temps</h3>", ">You're wasting time</h3>"),
    ("Vous gérez tout vous-meme — réseaux sociaux, site, emails — sans stratégie claire. Vos journees sont pleines mais les résultats ne suivent pas.",
     "You manage everything yourself — social media, website, emails — without a clear strategy. Your days are full but results don't follow."),
    (">Vos donnees sont inexploitées</h3>", ">Your data is untapped</h3>"),
    ("Vous ne savez pas d'ou viennent vos clients, quelles pages fonctionnent, ni pourquoi certains visiteurs n'achetent pas. Vous naviguez a vue.",
     "You don't know where your customers come from, which pages work, or why some visitors don't buy. You're flying blind."),

    # === VALUE PROPOSITION ===
    ("NOUS NE SOMMES PAS UNE AGENCE CLASSIQUE.", "WE ARE NOT A TRADITIONAL AGENCY."),
    ("NOUS SOMMES VOTRE PARTENAIRE DE CROISSANCE.", "WE ARE YOUR GROWTH PARTNER."),
    ("Depuis notre création, nous avons propulse plus de 150 entreprises vers la reussite digitale. Notre approche est stratégique, transparente et orientee résultats. Pas de jargon, pas de promesses en l'air — des chiffres qui parlent.",
     "Since our founding, we have propelled over 150 businesses towards digital success. Our approach is strategic, transparent and results-oriented. No jargon, no empty promises — numbers that speak for themselves."),
    (">Trafic organique moyen</p>", ">Average organic traffic</p>"),
    (">Projets livres</p>", ">Projects delivered</p>"),
    (">Projets livrés</p>", ">Projects delivered</p>"),
    (">Projets livr&eacute;s</p>", ">Projects delivered</p>"),
    (">SEO & Référencement Naturel</h4>", ">SEO & Organic Search</h4>"),
    ("Vous apparaissez en premier sur Google quand vos clients cherchent vos services. Plus de trafic qualifie, moins de dépendance a la pub.",
     "You appear first on Google when your customers search for your services. More qualified traffic, less dependence on ads."),
    (">Création de Sites Web</h4>", ">Website Creation</h4>"),
    (">Cr&eacute;ation de Sites Web</h4>", ">Website Creation</h4>"),
    ("Des sites rapides, beaux et qui convertissent vos visiteurs en clients. Webflow, WordPress, Shopify — on maitrise chaque plateforme.",
     "Fast, beautiful sites that convert your visitors into customers. Webflow, WordPress, Shopify — we master every platform."),
    (">IA & Automatisation</h4>", ">AI & Automation</h4>"),
    (">IA &amp; Automatisation</h4>", ">AI &amp; Automation</h4>"),
    ("Gagnez des heures chaque semaine grace a l'automatisation intelligente. Chatbots, workflows Make/N8N, agents IA sur mesure pour votre business.",
     "Save hours every week with intelligent automation. Chatbots, Make/N8N workflows, custom AI agents for your business."),

    # === SERVICES SECTION ===
    (">NOS EXPERTISES</h2>", ">OUR EXPERTISE</h2>"),
    (">SEO & REFERENCEMENT NATUREL</h3>", ">SEO & ORGANIC SEARCH</h3>"),
    (">SEO &amp; REFERENCEMENT NATUREL</h3>", ">SEO &amp; ORGANIC SEARCH</h3>"),
    ("Vous m&eacute;ritez d'&ecirc;tre trouv&eacute; sur Google. Nous vous amenons en premi&egrave;re page avec une strat&eacute;gie sur mesure, sans raccourcis.",
     "You deserve to be found on Google. We get you to the first page with a tailored strategy, no shortcuts."),
    (">CREATION DE SITES WEB</h3>", ">WEBSITE CREATION</h3>"),
    (">CR&Eacute;ATION DE SITES WEB</h3>", ">WEBSITE CREATION</h3>"),
    ("Des sites performants qui convertissent. Webflow, WordPress, Shopify ou sur mesure — chaque projet est unique, comme votre entreprise.",
     "High-performing sites that convert. Webflow, WordPress, Shopify or custom — every project is unique, like your business."),
    (">IA & AUTOMATISATION</h3>", ">AI & AUTOMATION</h3>"),
    (">IA &amp; AUTOMATISATION</h3>", ">AI &amp; AUTOMATION</h3>"),
    ("Gagnez du temps et de l'argent. On automatise vos processus repetitifs avec Make, N8N, Zapier et des agents IA sur mesure.",
     "Save time and money. We automate your repetitive processes with Make, N8N, Zapier and custom AI agents."),
    (">PUBLICITE PAYANTE (SEA & ADS)</h3>", ">PAID ADVERTISING (SEA & ADS)</h3>"),
    (">PUBLICITE PAYANTE (SEA &amp; ADS)</h3>", ">PAID ADVERTISING (SEA &amp; ADS)</h3>"),
    ("Des campagnes Google Ads, Meta Ads, TikTok et LinkedIn qui rapportent plus qu'elles ne coutent. Chaque euro investi est mesure.",
     "Google Ads, Meta Ads, TikTok and LinkedIn campaigns that earn more than they cost. Every euro invested is measured."),
    (">SOCIAL MEDIA</h3>", ">SOCIAL MEDIA</h3>"),
    ("Construisez une communauté engagée autour de votre marque. Stratégie, contenu, community management et influence marketing.",
     "Build an engaged community around your brand. Strategy, content, community management and influencer marketing."),
    (">DESIGN & BRANDING</h3>", ">DESIGN & BRANDING</h3>"),
    (">DESIGN &amp; BRANDING</h3>", ">DESIGN &amp; BRANDING</h3>"),
    ("Une identité visuelle forte qui vous différencie. Logo, charte graphique, direction artistique — on donne vie a votre vision.",
     "A strong visual identity that sets you apart. Logo, brand guidelines, art direction — we bring your vision to life."),
    ("Voir tous nos services ", "View all our services "),

    # === PROCESS (index) ===
    (">LE PROCESSUS ", ">THE "),
    (">PIRABEL</span>", ">PIRABEL PROCESS</span>"),
    (">Immersion</h5>", ">Immersion</h5>"),
    ("On apprend votre metier, vos objectifs et votre concurrence pour comprendre votre realite.",
     "We learn your business, your goals and your competition to understand your reality."),
    (">Diagnostic</h5>", ">Diagnosis</h5>"),
    ("Audit complet de votre presence digitale et identification des opportunites immediates.",
     "Complete audit of your digital presence and identification of immediate opportunities."),
    (">Stratégie</h5>", ">Strategy</h5>"),
    (">Strat&eacute;gie</h5>", ">Strategy</h5>"),
    ("On construit votre plan d'action personnalisé avec des objectifs clairs et mesurables.",
     "We build your personalized action plan with clear and measurable objectives."),
    (">Execution</h5>", ">Execution</h5>"),
    ("Deploiement méthodique de chaque action. Vous etes informe a chaque étape.",
     "Methodical deployment of each action. You are informed at every step."),
    (">Croissance</h5>", ">Growth</h5>"),
    ("Suivi continu, optimisation et expansion. Votre croissance est notre obsession.",
     "Continuous monitoring, optimization and expansion. Your growth is our obsession."),

    # === RESULTS ===
    (">PREUVES<br>", ">CONCRETE<br>"),
    (">CONCRETES</span>", ">PROOF</span>"),
    (">Selection 2025</p>", ">Selection 2025</p>"),
    (">E-COMMERCE MODE</h3>", ">FASHION E-COMMERCE</h3>"),
    ("+310% de leads qualifies en 6 mois", "+310% qualified leads in 6 months"),
    ("Refonte complete de l'architecture de contenu et stratégie de cocon sémantique. Le client a pu reduire son budget pub de 40%.",
     "Complete overhaul of content architecture and semantic cluster strategy. The client was able to reduce their ad budget by 40%."),
    (">CABINET IMMOBILIER</h3>", ">REAL ESTATE FIRM</h3>"),
    ("Position #1 sur 45 mots-cles locaux", "Position #1 on 45 local keywords"),
    ("Stratégie SEO local et Google Business optimise. Les demandes de visites ont triple en 4 mois.",
     "Local SEO strategy and optimized Google Business. Visit requests tripled in 4 months."),
    (">SAAS B2B</h3>", ">B2B SAAS</h3>"),
    ("Top 3 mondial sur 150+ keywords", "Top 3 worldwide on 150+ keywords"),
    ("Optimisation SEO technique avancee et stratégie de contenu expert. Le cout d'acquisition client divise par 3.",
     "Advanced technical SEO optimization and expert content strategy. Customer acquisition cost divided by 3."),

    # === TESTIMONIALS ===
    ("Pirabel Labs a transforme notre visibilité en ligne. En 6 mois, notre trafic organique a depasse nos campagnes payantes.",
     "Pirabel Labs transformed our online visibility. In 6 months, our organic traffic surpassed our paid campaigns."),
    ("On avait tout essaye avant. Deux agences, un freelance. Pirabel Labs a ete les premiers a tenir leurs promesses.",
     "We had tried everything before. Two agencies, a freelancer. Pirabel Labs were the first to keep their promises."),
    ("Le meilleur investissement marketing qu'on ait fait. Notre cout d'acquisition divise par 3.",
     "The best marketing investment we ever made. Our acquisition cost divided by 3."),
    ("Directrice Marketing", "Marketing Director"),
    ("CE QUE NOS CLIENTS DISENT", "WHAT OUR CLIENTS SAY"),

    # === COMPARISON TABLE ===
    (">FONCTIONNALITE</th>", ">FEATURE</th>"),
    (">AGENCE CLASSIQUE</th>", ">TRADITIONAL AGENCY</th>"),
    ("LES AUTRES</h2>", "THE OTHERS</h2>"),
    ("Garantie de résultats", "Results guarantee"),
    ("Garantie de r&eacute;sultats", "Results guarantee"),
    ("> Contractuelle</td>", "> Contractual</td>"),
    ("> Aucune</td>", "> None</td>"),
    ("Rapports comprehensibles", "Understandable reports"),
    ("> En langage clair</td>", "> In plain language</td>"),
    ("> Jargon technique</td>", "> Technical jargon</td>"),
    ("Contenu expert", "Expert content"),
    ("> IA non corrigee</td>", "> Uncorrected AI</td>"),
    ("Support reactif", "Responsive support"),
    ("> Reponse sous 24h</td>", "> Response within 24h</td>"),
    ("> Delais variables</td>", "> Variable delays</td>"),

    # === PRICING (index) ===
    ("INVESTISSEZ DANS VOTRE ", "INVEST IN YOUR "),
    (">EMPIRE.</span>", ">EMPIRE.</span>"),
    (">Fondation</h4>", ">Foundation</h4>"),
    ("Le plus demande", "Most popular"),
    ("Le plus demand&eacute;", "Most popular"),
    ("> Audit technique initial</li>", "> Initial technical audit</li>"),
    ("> Optimisation on-page</li>", "> On-page optimization</li>"),
    ("> 4 articles / mois</li>", "> 4 articles / month</li>"),
    ("> Reporting mensuel</li>", "> Monthly reporting</li>"),
    ("> Stratégie complete</li>", "> Complete strategy</li>"),
    ("> Strat&eacute;gie complete</li>", "> Complete strategy</li>"),
    ("> 8 articles / mois</li>", "> 8 articles / month</li>"),
    ("> Netlinking premium</li>", "> Premium netlinking</li>"),
    ("> ROI tracking avance</li>", "> Advanced ROI tracking</li>"),
    ("> Chef de projet dédié</li>", "> Dedicated project manager</li>"),
    ("> SEO multi-langue</li>", "> Multi-language SEO</li>"),
    ("> Migration accompagnee</li>", "> Assisted migration</li>"),
    ("> Account manager dédié</li>", "> Dedicated account manager</li>"),
    ("> Stratégie 360</li>", "> 360 Strategy</li>"),
    ("> Strat&eacute;gie 360</li>", "> 360 Strategy</li>"),
    (">Choisir ce plan</a>", ">Choose this plan</a>"),
    (">Prendre le controle</a>", ">Take control</a>"),
    (">Nous contacter</a>", ">Contact us</a>"),
    ("Sur Mesure", "Custom"),

    # === GUIDES (index) ===
    (">NOS GUIDES ", ">OUR GUIDES "),
    (">/ SAVOIR</span>", ">/ KNOWLEDGE</span>"),
    (">Guide SEO</span>", ">SEO Guide</span>"),
    (">Guide IA</span>", ">AI Guide</span>"),
    (">Guide Web</span>", ">Web Guide</span>"),
    (">Guide CRO</span>", ">CRO Guide</span>"),
    ("Le guide complet du SEO pour debutants", "The complete SEO guide for beginners"),
    ("Automatisation marketing avec l'IA", "Marketing automation with AI"),
    ("Webflow vs WordPress : quel CMS ?", "Webflow vs WordPress: which CMS?"),
    ("Anatomie d'une landing page parfaite", "Anatomy of a perfect landing page"),
    ("Guide gratuit", "Free guide"),
    ("Comparatif", "Comparison"),

    # === FAQ (index) ===
    (">QUESTIONS<br>", ">FREQUENTLY<br>"),
    (">FREQUENTES</span>", ">ASKED QUESTIONS</span>"),
    (">FR&Eacute;QUENTES</span>", ">ASKED QUESTIONS</span>"),
    (">FRÉQUENTES.</span>", ">ASKED QUESTIONS.</span>"),
    ("Combien de temps avant de voir des résultats ?", "How long before seeing results?"),
    ("Les premiers gains sont souvent visibles sous 30 jours pour les optimisations techniques. Pour un positionnement solide en première page, comptez 3 a 6 mois selon la concurrence de votre secteur.",
     "The first gains are often visible within 30 days for technical optimizations. For a solid first-page ranking, expect 3 to 6 months depending on your sector's competition."),
    ("Est-ce que vous travaillez avec tous types d'entreprises ?", "Do you work with all types of businesses?"),
    ("Oui. Startup, PME ou grande entreprise, nous adaptons notre approche. Nous travaillons avec des clients a Paris, Cotonou, Casablanca, Dakar, Bruxelles et Montreal.",
     "Yes. Startup, SME or large corporation, we adapt our approach. We work with clients in Paris, Cotonou, Casablanca, Dakar, Brussels and Montreal."),
    ("Quelle différence entre SEO et publicité payante ?", "What's the difference between SEO and paid advertising?"),
    ("Quelle diff&eacute;rence entre SEO et publicit&eacute; payante ?", "What's the difference between SEO and paid advertising?"),
    ("La publicité vous apporte du trafic tant que vous payez. Le SEO construit un actif durable : une fois bien positionne, votre site attire du trafic gratuitement pendant des mois voire des annees.",
     "Advertising brings you traffic as long as you pay. SEO builds a lasting asset: once well-positioned, your site attracts free traffic for months or even years."),
    ("Que comprend votre audit gratuit ?", "What does your free audit include?"),
    ("Analyse de votre visibilité actuelle, diagnostic technique, etude de vos concurrents et recommandations concretes. Vous recevez un document clair avec des actions prioritaires.",
     "Analysis of your current visibility, technical diagnosis, competitor study and concrete recommendations. You receive a clear document with priority actions."),

    # === CTA FINAL (index) ===
    ("PRET A DEVENIR<br>INCONTOURNABLE ?", "READY TO BECOME<br>UNSTOPPABLE?"),
    ("PR&Ecirc;T A DEVENIR<br>INCONTOURNABLE ?", "READY TO BECOME<br>UNSTOPPABLE?"),
    ("Reservez votre audit stratégique gratuit avec un de nos experts. C'est offert, sans engagement.",
     "Book your free strategic audit with one of our experts. It's free, no commitment."),
    ('placeholder="Votre email professionnel"', 'placeholder="Your professional email"'),
    (">Lancer l'audit</button>", ">Launch audit</button>"),

    # ==================== SERVICES.HTML ====================
    ("Services · 11 expertises · 10 march&eacute;s", "Services · 11 Expertises · 10 Markets"),
    ("Services · 11 expertises · 10 marchés", "Services · 11 Expertises · 10 Markets"),
    ("TOUT CE", "EVERYTHING"),
    ("QU'IL FAUT", "YOU NEED"),
    ("POUR DOMINER.", "TO DOMINATE."),
    ("Des solutions digitales intégrées, pensées pour votre business.", "Integrated digital solutions, designed for your business."),
    ("Des solutions digitales int&eacute;gr&eacute;es, pens&eacute;es pour votre business.", "Integrated digital solutions, designed for your business."),
    ("Stratégie, exécution, croissance", "Strategy, execution, growth"),
    ("nous gérons chaque levier pour maximiser votre retour sur investissement.", "we manage every lever to maximize your return on investment."),
    ("11 services premium,", "11 premium services,"),
    ("un seul objectif.", "one single objective."),
    ("Chaque service est personnalisé selon vos objectifs et votre marché. Aucun package générique — une stratégie taillée pour vous.",
     "Each service is customized to your goals and market. No generic packages — a strategy tailored for you."),
    ("Tous les services", "All Services"),
    ("Trafic &amp; Visibilit&eacute;", "Traffic &amp; Visibility"),
    ("Trafic & Visibilité", "Traffic & Visibility"),
    ("Conversion &amp; Ventes", "Conversion &amp; Sales"),
    ("Conversion & Ventes", "Conversion & Sales"),
    ("Contenu &amp; Design", "Content &amp; Design"),
    ("Contenu & Design", "Content & Design"),
    ("Tech &amp; IA", "Tech &amp; AI"),
    ("Tech & IA", "Tech & AI"),
    ("Service phare", "Flagship Service"),
    ("Voir ce service", "View this service"),
    ("Audit SEO technique complet", "Complete technical SEO audit"),
    ("Stratégie de mots-clés sur-mesure", "Custom keyword strategy"),
    ("Strat&eacute;gie de mots-cl&eacute;s sur-mesure", "Custom keyword strategy"),
    ("Netlinking premium &amp; autorité", "Premium link building &amp; authority"),
    ("Netlinking premium & autorité", "Premium link building & authority"),
    ("Core Web Vitals &amp; SEO technique avanc&eacute;", "Core Web Vitals &amp; advanced technical SEO"),
    ("Core Web Vitals & SEO technique avancé", "Core Web Vitals & advanced technical SEO"),
    ("Reporting mensuel avec KPIs d&eacute;finis", "Monthly reporting with defined KPIs"),
    ("Reporting mensuel avec KPIs définis", "Monthly reporting with defined KPIs"),
    ("A/B testing continu des créatifs", "Continuous A/B testing of creatives"),
    ("A/B testing continu des cr&eacute;atifs", "Continuous A/B testing of creatives"),
    ("Optimisation en temps réel", "Real-time optimization"),
    ("Optimisation en temps r&eacute;el", "Real-time optimization"),
    ("Stratégie éditoriale mensuelle", "Monthly editorial strategy"),
    ("Strat&eacute;gie &eacute;ditoriale mensuelle", "Monthly editorial strategy"),
    ("Création visuels, vidéos &amp; captions", "Visuals, videos &amp; captions creation"),
    ("Création visuels, vidéos & captions", "Visuals, videos & captions creation"),
    ("Community management actif", "Active community management"),
    ("Analytics &amp; reporting mensuel", "Analytics &amp; monthly reporting"),
    ("Analytics & reporting mensuel", "Analytics & monthly reporting"),
    ("Chatbots &amp; agents IA conversationnels", "Chatbots &amp; conversational AI agents"),
    ("Chatbots & agents IA conversationnels", "Chatbots & conversational AI agents"),
    ("Automatisation email, CRM &amp; workflows", "Email, CRM &amp; workflow automation"),
    ("Automatisation email, CRM & workflows", "Email, CRM & workflow automation"),
    ("Analyse prédictive &amp; lead scoring", "Predictive analytics &amp; lead scoring"),
    ("Analyse prédictive & lead scoring", "Predictive analytics & lead scoring"),
    ("Landing pages optimisées CRO", "CRO-optimized landing pages"),
    ("Landing pages optimis&eacute;es CRO", "CRO-optimized landing pages"),
    ("Tests A/B &amp; analyse heatmaps", "A/B testing &amp; heatmap analysis"),
    ("Tests A/B & analyse heatmaps", "A/B testing & heatmap analysis"),
    ("Design UI/UX sur-mesure", "Custom UI/UX design"),
    ("Développement front-end &amp; CMS", "Front-end development &amp; CMS"),
    ("Développement front-end & CMS", "Front-end development & CMS"),
    ("SEO-ready &amp; Core Web Vitals", "SEO-ready &amp; Core Web Vitals"),
    ("SEO-ready & Core Web Vitals", "SEO-ready & Core Web Vitals"),
    ("Maintenance &amp; support inclus", "Maintenance &amp; support included"),
    ("Maintenance & support inclus", "Maintenance & support included"),
    ("Audit UX &amp; performance", "UX &amp; performance audit"),
    ("Audit UX & performance", "UX & performance audit"),
    ("Redesign complet ou partiel", "Full or partial redesign"),
    ("Migration sans perte de trafic SEO", "Migration without SEO traffic loss"),
    ("Optimisation des conversions", "Conversion optimization"),
    ("Articles SEO optimisés", "SEO-optimized articles"),
    ("Articles SEO optimis&eacute;s", "SEO-optimized articles"),
    ("Newsletters &amp; email marketing", "Newsletters &amp; email marketing"),
    ("Scripts &amp; storyboards vid&eacute;o", "Video scripts &amp; storyboards"),
    ("Scripts & storyboards vidéo", "Video scripts & storyboards"),
    ("Montage &amp; post-production", "Editing &amp; post-production"),
    ("Montage & post-production", "Editing & post-production"),
    ("Motion design &amp; animations 2D", "Motion design &amp; 2D animations"),
    ("Motion design & animations 2D", "Motion design & 2D animations"),
    ("Reels, shorts &amp; contenus courts", "Reels, shorts &amp; short-form content"),
    ("Reels, shorts & contenus courts", "Reels, shorts & short-form content"),
    ("Branding &amp; charte graphique", "Branding &amp; complete style guide"),
    ("Branding & charte graphique", "Branding & complete style guide"),
    ("UI/UX design d'interface", "UI/UX interface design"),
    ("UI/UX design d&#39;interface", "UI/UX interface design"),
    ("Supports print &amp; digital", "Print &amp; digital materials"),
    ("Supports print & digital", "Print & digital materials"),
    ("Déclinaisons réseaux sociaux", "Social media adaptations"),
    ("D&eacute;clinaisons r&eacute;seaux sociaux", "Social media adaptations"),
    ("Audit &amp; restructuration CRM", "CRM audit &amp; restructuring"),
    ("Audit & restructuration CRM", "CRM audit & restructuring"),
    ("Séquences d'automation sur-mesure", "Custom automation sequences"),
    ("S&eacute;quences d&#39;automation sur-mesure", "Custom automation sequences"),
    ("Design templates email premium", "Premium email template design"),
    ("A/B testing &amp; optimisation taux ouverture", "A/B testing &amp; open rate optimization"),
    ("A/B testing & optimisation taux ouverture", "A/B testing & open rate optimization"),
    ("Sur devis", "Custom quote"),

    # Pricing labels
    ("par mois · engagement 3 mois min.", "per month · 3-month minimum commitment"),
    ("Commencer →", "Get Started →"),
    ("Recommandé", "Recommended"),
    ("Recommand&eacute;", "Recommended"),
    ("Démarrer ma croissance →", "Start my growth →"),
    ("D&eacute;marrer ma croissance →", "Start my growth →"),
    ("Nous contacter →", "Contact us →"),
    ("adapté à votre échelle", "adapted to your scale"),
    ("adapt&eacute; &agrave; votre &eacute;chelle", "adapted to your scale"),
    ("Satisfait ou rembourse 30 jours", "Satisfied or refunded within 30 days"),
    ("Satisfait ou rembours&eacute; 30 jours", "Satisfied or refunded within 30 days"),

    # Process (services)
    ("Comment ça marche", "How It Works"),
    ("Comment &ccedil;a marche", "How It Works"),
    ("Notre processus", "Our process"),
    ("en 5 étapes claires.", "in 5 clear steps."),
    ("en 5 &eacute;tapes claires.", "in 5 clear steps."),
    ("Découverte &amp; Audit", "Discovery &amp; Audit"),
    ("Découverte & Audit", "Discovery & Audit"),
    ("Livrable sous 7 jours", "Deliverable within 7 days"),
    ("Stratégie &amp; Roadmap 90 jours", "Strategy &amp; 90-Day Roadmap"),
    ("Stratégie & Roadmap 90 jours", "Strategy & 90-Day Roadmap"),
    ("Validation avant démarrage", "Validation before launch"),
    ("Validation avant d&eacute;marrage", "Validation before launch"),
    ("Exécution par des experts", "Execution by experts"),
    ("Ex&eacute;cution par des experts", "Execution by experts"),
    ("Communication hebdomadaire", "Weekly communication"),
    ("Optimisation Continue", "Continuous Optimization"),
    ("A/B testing permanent", "Permanent A/B testing"),
    ("Scaling &amp; Croissance", "Scaling &amp; Growth"),
    ("Scaling & Croissance", "Scaling & Growth"),
    ("Croissance exponentielle", "Exponential growth"),

    # Form labels
    ("Audit gratuit · Sans engagement", "Free Audit · No Commitment"),
    ("Audit gratuit &middot; Sans engagement", "Free Audit &middot; No Commitment"),
    ("Parlons de", "Let's talk about"),
    ("votre projet.", "your project."),
    ("Envoyer ma demande", "Send My Request"),
    ("Réponse sous 24h · Aucun spam · Données sécurisées", "Response within 24h · No spam · Secure data"),
    ("R&eacute;ponse sous 24h", "Response within 24h"),
    ("Réponse sous 24h", "Response within 24h"),
    ("Données sécurisées", "Secure data"),
    ("Donn&eacute;es s&eacute;curis&eacute;es", "Secure data"),
    ("Sans engagement", "No commitment"),
    ("Aucun engagement", "No commitment"),
    ("Sélectionner...", "Select..."),
    ("S&eacute;lectionner...", "Select..."),
    ("Choisissez un service", "Choose a service"),
    ("Je ne sais pas encore", "I don't know yet"),
    ("Plusieurs services", "Multiple services"),
    ("Autre / À définir", "Other / To be defined"),
    ("Autre / &Agrave; d&eacute;finir", "Other / To be defined"),
    ("À définir ensemble", "To be defined together"),
    ("&Agrave; d&eacute;finir ensemble", "To be defined together"),
    ('placeholder="Votre nom"', 'placeholder="Your name"'),
    ('placeholder="Votre nom et prénom"', 'placeholder="Your full name"'),
    ('placeholder="Votre entreprise"', 'placeholder="Your company"'),
    ('placeholder="Votre message"', 'placeholder="Your message"'),
    ('placeholder="votre.email@entreprise.com"', 'placeholder="your.email@company.com"'),
    ("Nom complet", "Full name"),
    ("Email professionnel", "Professional email"),
    ("Prénom", "First Name"),
    ("Pr&eacute;nom", "First Name"),
    ("Téléphone", "Phone"),
    ("T&eacute;l&eacute;phone", "Phone"),
    ("Site web actuel", "Current website"),
    ("Site web", "Website"),
    ("Budget mensuel estimé", "Estimated monthly budget"),
    ("Budget mensuel estim&eacute;", "Estimated monthly budget"),
    ("Budget mensuel envisagé", "Estimated monthly budget"),
    ("Budget mensuel envisag&eacute;", "Estimated monthly budget"),
    ("Service souhaité", "Desired service"),
    ("Service souhait&eacute;", "Desired service"),
    ("Votre objectif principal", "Your main objective"),
    ("Parlez-nous de votre projet", "Tell us about your project"),
    ("Recevoir mon audit gratuit", "Get my free audit"),
    ("Envoyer ma demande ↗", "Send My Request"),

    # Select options
    ("Moins de 1 000&euro;/mois", "Less than 1,000/month"),
    ("Moins de 1 000€/mois", "Less than 1,000/month"),
    ("1 000&euro; - 3 000&euro;/mois", "1,000 - 3,000/month"),
    ("1 000€ - 3 000€/mois", "1,000 - 3,000/month"),
    ("3 000&euro; - 5 000&euro;/mois", "3,000 - 5,000/month"),
    ("3 000€ - 5 000€/mois", "3,000 - 5,000/month"),
    ("Plus de 5 000&euro;/mois", "More than 5,000/month"),
    ("Plus de 5 000€/mois", "More than 5,000/month"),
    ("Sélectionnez", "Select"),
    ("S&eacute;lectionnez", "Select"),
    ("Formule complète Growth", "Complete Growth Plan"),
    ("Formule compl&egrave;te Growth", "Complete Growth Plan"),
    ("Création de site web", "Website creation"),
    ("Cr&eacute;ation de site web", "Website creation"),

    # ==================== CONTACT.HTML ====================
    ("PARLONS", "LET'S TALK"),
    ("DE VOTRE", "ABOUT YOUR"),
    ("FUTUR.", "FUTURE."),
    ("Nos bureaux", "Our Offices"),
    ("Cotonou, B&eacute;nin", "Cotonou, Benin"),
    ("Cotonou, Bénin", "Cotonou, Benin"),
    ("Casablanca, Maroc", "Casablanca, Morocco"),
    ("Montréal, Canada", "Montreal, Canada"),
    ("Montr&eacute;al, Canada", "Montreal, Canada"),
    ("Notre réseau mondial", "Our Global Network"),
    ("Notre r&eacute;seau mondial", "Our Global Network"),
    ("NOTRE RÉSEAU", "OUR NETWORK"),
    ("NOTRE R&Eacute;SEAU", "OUR NETWORK"),
    ("Belgique", "Belgium"),
    ("Bénin", "Benin"),
    ("B&eacute;nin", "Benin"),
    ("Maroc", "Morocco"),
    ("Sénégal", "Senegal"),
    ("S&eacute;n&eacute;gal", "Senegal"),
    ("Côte d'Ivoire", "Ivory Coast"),
    ("C&ocirc;te d&#39;Ivoire", "Ivory Coast"),
    ("Tunisie", "Tunisia"),
    ("Demande envoyée avec succès", "Request sent successfully"),
    ("Demande envoy&eacute;e avec succ&egrave;s", "Request sent successfully"),
    ("Nous vous recontactons sous 24h", "We will contact you within 24h"),

    # ==================== A-PROPOS.HTML ====================
    ("À propos de Pirabel Labs", "About Pirabel Labs"),
    ("&Agrave; propos de Pirabel Labs", "About Pirabel Labs"),
    ("L'OBSESSION", "THE OBSESSION"),
    ("DE LA", "WITH"),
    ("PERFORMANCE.", "PERFORMANCE."),
    ("Notre manifeste", "Our Manifesto"),
    ("UNE ARCHITECTURE DIGITALE QUI DURE", "A DIGITAL ARCHITECTURE THAT LASTS"),
    ("CE QUI NOUS GUIDE AU QUOTIDIEN", "WHAT GUIDES US EVERY DAY"),
    ("Transparence totale", "Total Transparency"),
    ("Résultats mesurables", "Measurable Results"),
    ("R&eacute;sultats mesurables", "Measurable Results"),
    ("Partenariat long terme", "Long-Term Partnership"),
    ("L'équipe", "The Team"),
    ("L&#39;&eacute;quipe", "The Team"),
    ("L'ÉLITE COLLECTIVE", "THE COLLECTIVE ELITE"),
    ("L&#39;&Eacute;LITE COLLECTIVE", "THE COLLECTIVE ELITE"),
    ("REJOIGNEZ L'ÉLITE.", "JOIN THE ELITE."),
    ("REJOIGNEZ L&#39;&Eacute;LITE.", "JOIN THE ELITE."),
    ("Fondateur &amp; CEO", "Founder &amp; CEO"),
    ("Fondateur & CEO", "Founder & CEO"),
    ("Stratégie &amp; Vision", "Strategy &amp; Vision"),
    ("Stratégie & Vision", "Strategy & Vision"),
    ("Référencement &amp; Contenu", "SEO &amp; Content"),
    ("Référencement & Contenu", "SEO & Content"),
    ("Tech &amp; Automatisation", "Tech &amp; Automation"),
    ("Tech & Automatisation", "Tech & Automation"),
    ("Directrice Artistique", "Art Director"),
    ("Clients actifs", "Active Clients"),
    ("Villes couvertes", "Cities Covered"),
    ("Satisfaction client", "Client Satisfaction"),
    ("Notre histoire", "Our story"),
    ("Notre mission", "Our mission"),
    ("Nos valeurs", "Our values"),

    # ==================== FAQ.HTML ====================
    ("Questions fréquentes", "Frequently Asked Questions"),
    ("Questions fr&eacute;quentes", "Frequently Asked Questions"),
    (">QUESTIONS", ">FREQUENTLY"),
    ("Quels services proposez-vous ?", "What services do you offer?"),
    ("Dans quelles villes intervenez-vous ?", "In which cities do you operate?"),
    ("Comment démarrer avec Pirabel Labs ?", "How do I get started with Pirabel Labs?"),
    ("Comment d&eacute;marrer avec Pirabel Labs ?", "How do I get started with Pirabel Labs?"),
    ("Tarifs &amp; Délais", "Pricing &amp; Timelines"),
    ("Tarifs & Délais", "Pricing & Timelines"),
    ("Combien coûtent vos services ?", "How much do your services cost?"),
    ("Combien co&ucirc;tent vos services ?", "How much do your services cost?"),
    ("Combien de temps pour voir des résultats ?", "How long to see results?"),
    ("Y a-t-il un engagement minimum ?", "Is there a minimum commitment?"),
    ("Processus &amp; Collaboration", "Process &amp; Collaboration"),
    ("Processus & Collaboration", "Process & Collaboration"),
    ("Comment se passe la collaboration au quotidien ?", "How does day-to-day collaboration work?"),
    ("Quelles garanties offrez-vous ?", "What guarantees do you offer?"),
    ("Est-ce que je garde la propriété de mon site et de mes comptes ?", "Do I keep ownership of my website and accounts?"),
    ("Est-ce que je garde la propri&eacute;t&eacute; de mon site et de mes comptes ?", "Do I keep ownership of my website and accounts?"),
    ("UNE QUESTION RESTÉE SANS RÉPONSE ?", "A QUESTION LEFT UNANSWERED?"),
    ("UNE QUESTION REST&Eacute;E SANS R&Eacute;PONSE ?", "A QUESTION LEFT UNANSWERED?"),
    ("Écrivez-nous, nous répondons sous 24h.", "Write to us, we respond within 24h."),
    ("&Eacute;crivez-nous, nous r&eacute;pondons sous 24h.", "Write to us, we respond within 24h."),

    # ==================== RESULTATS.HTML ====================
    ("ÉTUDES", "CASE"),
    ("&Eacute;TUDES", "CASE"),
    ("DE CAS.", "STUDIES."),
    ("Études de cas", "Case Studies"),
    ("&Eacute;tudes de cas", "Case Studies"),
    ("Trafic moyen", "Average Traffic"),
    ("ROI moyen", "Average ROI"),
    ("VOUS VOULEZ DES RÉSULTATS COMME CEUX-LÀ ?", "DO YOU WANT RESULTS LIKE THESE?"),
    ("VOUS VOULEZ DES R&Eacute;SULTATS COMME CEUX-L&Agrave; ?", "DO YOU WANT RESULTS LIKE THESE?"),

    # ==================== BLOG.HTML ====================
    ("Blog &amp; Actualités", "Blog &amp; News"),
    ("Blog & Actualités", "Blog & News"),
    ("LE BLOG", "THE BLOG"),
    ("PIRABEL LABS.", "PIRABEL LABS."),
    ("Articles populaires", "Popular Articles"),
    ("Lire l'article", "Read the article"),
    ("Lire l&#39;article", "Read the article"),
    ("Articles récents", "Recent articles"),
    ("Articles r&eacute;cents", "Recent articles"),
    ("Tous les articles", "All articles"),
    ("min de lecture", "min read"),
    (">Tous</", ">All</"),
    (">Publicité</", ">Advertising</"),
    (">Publicit&eacute;</", ">Advertising</"),
    (">Vidéo</", ">Video</"),
    (">Vid&eacute;o</", ">Video</"),

    # Blog article titles (common ones)
    ("Branding et Identité Visuelle", "Branding and Visual Identity"),
    ("Branding et Identit&eacute; Visuelle", "Branding and Visual Identity"),
    ("Automatisation Marketing", "Marketing Automation"),
    ("Publicité en Ligne", "Online Advertising"),
    ("Publicit&eacute; en Ligne", "Online Advertising"),
    ("Stratégie Social Media", "Social Media Strategy"),
    ("Strat&eacute;gie Social Media", "Social Media Strategy"),
    ("Création de Site Web Professionnel", "Professional Website Creation"),
    ("Cr&eacute;ation de Site Web Professionnel", "Professional Website Creation"),
    ("L'Intelligence Artificielle dans le Marketing Digital", "Artificial Intelligence in Digital Marketing"),
    ("L&#39;Intelligence Artificielle dans le Marketing Digital", "Artificial Intelligence in Digital Marketing"),
    ("SEO et Référencement Naturel", "SEO and Organic Search"),
    ("SEO et R&eacute;f&eacute;rencement Naturel", "SEO and Organic Search"),
    ("Email Marketing", "Email Marketing"),
    ("WordPress vs Shopify", "WordPress vs Shopify"),
    ("Chatbot IA", "AI Chatbot"),
    ("TikTok Marketing", "TikTok Marketing"),
    ("Content Marketing", "Content Marketing"),
    ("SEO Local", "Local SEO"),
    ("Vidéo Marketing", "Video Marketing"),
    ("Vid&eacute;o Marketing", "Video Marketing"),
    ("Optimisation du Taux de Conversion", "Conversion Rate Optimization"),
    ("LinkedIn Marketing B2B", "LinkedIn B2B Marketing"),
    ("Google Analytics 4", "Google Analytics 4"),
    ("Tunnels de Vente", "Sales Funnels"),
    ("UX Design", "UX Design"),
    ("Copywriting", "Copywriting"),
    ("Netlinking et Backlinks", "Link Building and Backlinks"),
    ("Core Web Vitals", "Core Web Vitals"),
    ("Le Guide Complet", "The Complete Guide"),
    ("Les Étapes Essentielles", "The Essential Steps"),
    ("Les &Eacute;tapes Essentielles", "The Essential Steps"),
    ("Les Tendances Incontournables", "The Must-Know Trends"),
    ("Les Techniques de Persuasion", "Persuasion Techniques"),
    ("Guide Complet", "Complete Guide"),
    ("Guide complet", "Complete guide"),
    ("Guide D&eacute;butant", "Beginner's Guide"),
    ("Guide Débutant", "Beginner's Guide"),

    # ==================== CITY PAGES (common patterns) ====================
    ("Le problème", "The problem"),
    ("Le probl&egrave;me", "The problem"),
    ("EST-CE QUE CA VOUS PARLE ?", "DOES THIS SOUND FAMILIAR?"),
    ("EST-CE QUE &Ccedil;A VOUS PARLE ?", "DOES THIS SOUND FAMILIAR?"),
    ("Notre approche", "Our approach"),
    ("LES CHIFFRES PARLENT D'EUX-MEMES", "THE NUMBERS SPEAK FOR THEMSELVES"),
    ("LES CHIFFRES PARLENT D&#39;EUX-M&Ecirc;MES", "THE NUMBERS SPEAK FOR THEMSELVES"),
    ("Nos réalisations", "Our work"),
    ("Nos r&eacute;alisations", "Our work"),
    ("Nos résultats", "Our results"),
    ("Nos r&eacute;sultats", "Our results"),
    ("Témoignages", "Testimonials"),
    ("T&eacute;moignages", "Testimonials"),
    ("Investissement", "Investment"),
    ("Populaire", "Popular"),
    ("Essentiel", "Essential"),
    ("Premium", "Premium"),
    ("Guides &amp; Ressources", "Guides &amp; Resources"),
    ("Guides & Ressources", "Guides & Resources"),
    ("Services complémentaires", "Complementary services"),
    ("Services compl&eacute;mentaires", "Complementary services"),
    (">Découvrir</a>", ">Discover</a>"),
    (">D&eacute;couvrir</a>", ">Discover</a>"),
    ("Nos villes", "Our cities"),
    ("NOUS INTERVENONS DANS CES VILLES", "WE WORK IN THESE CITIES"),
    ("Nous intervenons aussi dans ces villes", "We also work in these cities"),
    ("Où que vous soyez, nous sommes là.", "Wherever you are, we're here."),
    ("O&ugrave; que vous soyez, nous sommes l&agrave;.", "Wherever you are, we're here."),
    ("EXPERTISE LOCALE", "LOCAL EXPERTISE"),
    ("Première page Google", "First page of Google"),
    ("Premi&egrave;re page Google", "First page of Google"),
    ("Sites qui convertissent.", "Websites that convert."),
    ("Automatisez vos process.", "Automate your processes."),
    ("ROI maximal.", "Maximum ROI."),
    ("Communauté engagée.", "Engaged community."),
    ("Communaut&eacute; engag&eacute;e.", "Engaged community."),
    ("Identité visuelle forte.", "Strong visual identity."),
    ("Identit&eacute; visuelle forte.", "Strong visual identity."),
    ("QUESTIONS FREQUENTES", "FREQUENTLY ASKED QUESTIONS"),

    # City page FAQ answers
    ("Nous combinons expertise technique et connaissance du marché", "We combine technical expertise and knowledge of the market"),
    ("Nos résultats sont mesurables et nous nous engageons sur des objectifs précis.", "Our results are measurable and we commit to specific goals."),
    ("Nos r&eacute;sultats sont mesurables et nous nous engageons sur des objectifs pr&eacute;cis.", "Our results are measurable and we commit to specific goals."),
    ("Nos tarifs dependent de vos besoins. Nous proposons un audit gratuit pour une estimation precise. Contactez-nous.",
     "Our rates depend on your needs. We offer a free audit for a precise estimate. Contact us."),
    ("Nos tarifs d&eacute;pendent de vos besoins. Nous proposons un audit gratuit pour une estimation pr&eacute;cise. Contactez-nous.",
     "Our rates depend on your needs. We offer a free audit for a precise estimate. Contact us."),
    ("Premiers résultats en 30 a 90 jours selon le service. SEO : 3 a 6 mois. Publicité et social : plus rapides.",
     "First results in 30 to 90 days depending on the service. SEO: 3 to 6 months. Advertising and social: faster."),
    ("Premiers r&eacute;sultats en 30 &agrave; 90 jours selon le service. SEO : 3 &agrave; 6 mois. Publicit&eacute; et social : plus rapides.",
     "First results in 30 to 90 days depending on the service. SEO: 3 to 6 months. Advertising and social: faster."),

    # City CTA
    ("Audit gratuit — on analyse votre situation et on vous montre comment accelerer.",
     "Free audit — we analyze your situation and show you how to accelerate."),
    ("Audit gratuit &mdash; on analyse votre situation et on vous montre comment acc&eacute;l&eacute;rer.",
     "Free audit — we analyze your situation and show you how to accelerate."),
    ("Demander mon audit gratuit", "Request my free audit"),

    # ==================== WEB SERVICE PAGES ====================
    ("UN SITE QUI CONVERTIT", "A WEBSITE THAT CONVERTS"),
    ("VOS VISITEURS", "YOUR VISITORS"),
    ("EN CLIENTS.", "INTO CLIENTS."),
    ("ON NE FAIT PAS DES SITES WEB.", "WE DON'T MAKE WEBSITES."),
    ("ON CONSTRUIT DES MACHINES A CONVERTIR.", "WE BUILD CONVERSION MACHINES."),
    ("ON CONSTRUIT DES MACHINES &Agrave; CONVERTIR.", "WE BUILD CONVERSION MACHINES."),
    ("UNE SOLUTION POUR CHAQUE TYPE DE PROJET", "A SOLUTION FOR EVERY TYPE OF PROJECT"),
    ("Expertise phare", "Key expertise"),
    ("En savoir plus", "Learn more"),
    ("COMMENT ON CREE VOTRE SITE WEB", "HOW WE BUILD YOUR WEBSITE"),
    ("COMMENT ON CR&Eacute;E VOTRE SITE WEB", "HOW WE BUILD YOUR WEBSITE"),
    ("Brief &amp; Découverte", "Brief &amp; Discovery"),
    ("Brief & Découverte", "Brief & Discovery"),
    ("Développement", "Development"),
    ("D&eacute;veloppement", "Development"),
    ("Tests &amp; Optimisation", "Testing &amp; Optimization"),
    ("Tests & Optimisation", "Testing & Optimization"),
    ("Lancement &amp; Suivi", "Launch &amp; Follow-up"),
    ("Lancement & Suivi", "Launch & Follow-up"),
    ("DES SITES QUI GENERENT DES RESULTATS CONCRETS", "WEBSITES THAT GENERATE CONCRETE RESULTS"),
    ("DES SITES QUI G&Eacute;N&Egrave;RENT DES R&Eacute;SULTATS CONCRETS", "WEBSITES THAT GENERATE CONCRETE RESULTS"),
    ("Site vitrine professionnel", "Professional showcase website"),
    ("Site e-commerce ou multi-pages", "E-commerce or multi-page site"),
    ("Plateforme ou application complexe", "Complex platform or application"),
    ("Lancer mon projet", "Launch my project"),
    ("Prix final, sans frais caches", "Final price, no hidden fees"),
    ("Prix final, sans frais cach&eacute;s", "Final price, no hidden fees"),
    ("Livraison en 3 a 6 semaines", "Delivery in 3 to 6 weeks"),
    ("Livraison en 3 &agrave; 6 semaines", "Delivery in 3 to 6 weeks"),
    ("PRET A LANCER VOTRE SITE ?", "READY TO LAUNCH YOUR WEBSITE?"),
    ("PR&Ecirc;T &Agrave; LANCER VOTRE SITE ?", "READY TO LAUNCH YOUR WEBSITE?"),
    ("Voir nos realisations", "See our work"),
    ("Voir nos r&eacute;alisations", "See our work"),
    ("Conversions en moyenne", "Average conversions"),
    ("Sites livres", "Websites delivered"),
    ("Sites livr&eacute;s", "Websites delivered"),
    ("Temps chargement moyen", "Average loading time"),
    ("Satisfaction clients", "Client satisfaction"),

    # ==================== SEO SERVICE PAGES ====================
    ("VOUS MERITEZ", "YOU DESERVE"),
    ("VOUS M&Eacute;RITEZ", "YOU DESERVE"),
    ("LA PREMIERE PAGE", "THE FIRST PAGE"),
    ("LA PREMI&Egrave;RE PAGE", "THE FIRST PAGE"),
    ("DE GOOGLE.", "OF GOOGLE."),
    ("ON NE FAIT PAS DU SEO.", "WE DON'T DO SEO."),
    ("ON CONSTRUIT VOTRE MACHINE A TRAFIC.", "WE BUILD YOUR TRAFFIC MACHINE."),
    ("ON CONSTRUIT VOTRE MACHINE &Agrave; TRAFIC.", "WE BUILD YOUR TRAFFIC MACHINE."),
    ("DES SOLUTIONS POUR CHAQUE DIMENSION DE VOTRE REFERENCEMENT", "SOLUTIONS FOR EVERY DIMENSION OF YOUR SEARCH RANKINGS"),
    ("DES SOLUTIONS POUR CHAQUE DIMENSION DE VOTRE R&Eacute;F&Eacute;RENCEMENT", "SOLUTIONS FOR EVERY DIMENSION OF YOUR SEARCH RANKINGS"),
    ("COMMENT ON VOUS AMENE EN PREMIERE PAGE", "HOW WE GET YOU TO THE FIRST PAGE"),
    ("COMMENT ON VOUS AM&Egrave;NE EN PREMI&Egrave;RE PAGE", "HOW WE GET YOU TO THE FIRST PAGE"),
    ("Audit &amp; Découverte", "Audit &amp; Discovery"),
    ("Audit & Découverte", "Audit & Discovery"),
    ("Audit &amp; D&eacute;couverte", "Audit &amp; Discovery"),
    ("Stratégie &amp; Roadmap", "Strategy &amp; Roadmap"),
    ("Stratégie & Roadmap", "Strategy & Roadmap"),
    ("Strat&eacute;gie &amp; Roadmap", "Strategy &amp; Roadmap"),
    ("Optimisation Technique", "Technical Optimization"),
    ("Contenu &amp; Netlinking", "Content &amp; Link Building"),
    ("Contenu & Netlinking", "Content & Link Building"),
    ("Suivi &amp; Croissance", "Monitoring &amp; Growth"),
    ("Suivi & Croissance", "Monitoring & Growth"),
    ("Trafic moyen genere", "Average traffic generated"),
    ("Trafic moyen g&eacute;n&eacute;r&eacute;", "Average traffic generated"),
    ("Mots-cles en top 3", "Keywords in top 3"),
    ("Mots-cl&eacute;s en top 3", "Keywords in top 3"),
    ("Delai résultats visibles", "Time to visible results"),
    ("D&eacute;lai r&eacute;sultats visibles", "Time to visible results"),
    ("Audit SEO Gratuit", "Free SEO Audit"),
    ("Voir nos résultats", "See our results"),
    ("Voir nos r&eacute;sultats", "See our results"),
    ("PRET A DOMINER GOOGLE ?", "READY TO DOMINATE GOOGLE?"),
    ("PR&Ecirc;T &Agrave; DOMINER GOOGLE ?", "READY TO DOMINATE GOOGLE?"),
    ("Résultats des le 3eme mois", "Results from the 3rd month"),
    ("R&eacute;sultats d&egrave;s le 3&egrave;me mois", "Results from the 3rd month"),

    # ==================== DESIGN SERVICE PAGES ====================
    ("UNE MARQUE FORTE", "A STRONG BRAND"),
    ("COMMENCE PAR UN", "STARTS WITH"),
    ("DESIGN MEMORABLE.", "MEMORABLE DESIGN."),
    ("DESIGN M&Eacute;MORABLE.", "MEMORABLE DESIGN."),
    ("ON NE FAIT PAS DU GRAPHISME.", "WE DON'T DO GRAPHIC DESIGN."),
    ("ON CONSTRUIT DES MARQUES QUI DURENT.", "WE BUILD BRANDS THAT LAST."),
    ("DES SOLUTIONS POUR CHAQUE DIMENSION DE VOTRE MARQUE", "SOLUTIONS FOR EVERY DIMENSION OF YOUR BRAND"),
    ("COMMENT NAIT VOTRE IDENTITE DE MARQUE", "HOW YOUR BRAND IDENTITY IS BORN"),
    ("COMMENT NA&Icirc;T VOTRE IDENTIT&Eacute; DE MARQUE", "HOW YOUR BRAND IDENTITY IS BORN"),
    ("Découverte &amp; Brief", "Discovery &amp; Brief"),
    ("Découverte & Brief", "Discovery & Brief"),
    ("D&eacute;couverte &amp; Brief", "Discovery &amp; Brief"),
    ("Recherche &amp; Moodboard", "Research &amp; Moodboard"),
    ("Recherche & Moodboard", "Research & Moodboard"),
    ("Concepts &amp; Design", "Concepts &amp; Design"),
    ("Concepts & Design", "Concepts & Design"),
    ("Revisions &amp; Finalisation", "Revisions &amp; Finalization"),
    ("Revisions & Finalisation", "Revisions & Finalization"),
    ("Livraison &amp; Guide", "Delivery &amp; Guide"),
    ("Livraison & Guide", "Delivery & Guide"),
    ("Identité Complete", "Complete Identity"),
    ("Identit&eacute; Compl&egrave;te", "Complete Identity"),
    ("Construire ma marque", "Build my brand"),
    ("Fichiers sources inclus", "Source files included"),
    ("Livraison 3 a 5 semaines", "Delivery 3 to 5 weeks"),
    ("Livraison 3 &agrave; 5 semaines", "Delivery 3 to 5 weeks"),
    ("PRET A CONSTRUIRE VOTRE MARQUE ?", "READY TO BUILD YOUR BRAND?"),
    ("PR&Ecirc;T &Agrave; CONSTRUIRE VOTRE MARQUE ?", "READY TO BUILD YOUR BRAND?"),
    ("Consultation Gratuite", "Free Consultation"),
    ("Demander une consultation gratuite", "Request a free consultation"),
    ("Recevoir ma consultation gratuite", "Get my free consultation"),
    ("Voir nos creations", "See our creations"),
    ("Voir nos cr&eacute;ations", "See our creations"),
    ("Identités créées", "Identities created"),
    ("Identit&eacute;s cr&eacute;&eacute;es", "Identities created"),
    ("Logos créés", "Logos created"),
    ("Logos cr&eacute;&eacute;s", "Logos created"),
    ("Secteurs d'activité", "Industries covered"),
    ("Secteurs d&#39;activit&eacute;", "Industries covered"),

    # ==================== CAREERS / LEGAL ====================
    ("Rejoignez-nous", "Join us"),
    ("Rejoignez notre &eacute;quipe", "Join our team"),
    ("Rejoignez notre équipe", "Join our team"),
    ("Postuler", "Apply"),
    ("Voir l'offre", "View offer"),
    ("Voir l&#39;offre", "View offer"),
    ("Offres d'emploi", "Job offers"),
    ("Offres d&#39;emploi", "Job offers"),

    # ==================== COMMON BUTTONS & SHORT LABELS ====================
    (">Contactez-nous</a>", ">Contact us</a>"),
    (">Demander un audit gratuit</a>", ">Request a free audit</a>"),
    (">Demander un devis</a>", ">Request a quote</a>"),
    (">En savoir plus</a>", ">Learn more</a>"),
    (">Voir nos résultats</a>", ">See our results</a>"),
    (">Voir nos r&eacute;sultats</a>", ">See our results</a>"),
    (">Prendre rendez-vous</a>", ">Book an appointment</a>"),
    (">Retour</a>", ">Back</a>"),
    (">Envoyer</button>", ">Send</button>"),
    (">Envoyer le message</button>", ">Send message</button>"),
    (">Tous les articles</a>", ">All articles</a>"),
    ("Nous contacter", "Contact us"),
    ("Demander un audit gratuit", "Request a free audit"),
    ("Audit gratuit ↗", "Free Audit"),
    ("Audit gratuit", "Free audit"),

    # Common phrases
    ("solutions sur mesure", "tailored solutions"),
    ("sur mesure", "tailored"),
    ("Nos clients", "Our clients"),
    ("Nos services", "Our services"),
    ("Nos expertises", "Our expertise"),
    ("Notre approche", "Our approach"),
    ("Notre équipe", "Our team"),
    ("Notre &eacute;quipe", "Our team"),
    ("Agence digitale premium", "Premium digital agency"),
    ("/mois", "/month"),
]

# Regex-based for meta titles
META_RE = [
    (r'(<title>[^<]*?)Agence Digitale Premium([^<]*?</title>)',
     r'\1Premium Digital Agency\2'),
]


def translate_file(src_path, dest_path):
    with open(src_path, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    for fr, en in T:
        content = content.replace(fr, en)

    for pattern, repl in META_RE:
        content = re.sub(pattern, repl, content)

    # Fix internal links for /en/ routing
    link_map = {
        'href="/"': 'href="/en/"',
        "href='/'": "href='/en/'",
        'href="/services"': 'href="/en/services"',
        'href="/blog"': 'href="/en/blog"',
        'href="/resultats"': 'href="/en/resultats"',
        'href="/r&eacute;sultats"': 'href="/en/resultats"',
        'href="/résultats"': 'href="/en/resultats"',
        'href="/a-propos"': 'href="/en/a-propos"',
        'href="/contact"': 'href="/en/contact"',
        'href="/faq"': 'href="/en/faq"',
        'href="/carrieres"': 'href="/en/carrieres"',
        'href="/carrières"': 'href="/en/carrieres"',
        'href="/mentions-legales"': 'href="/en/mentions-legales"',
        'href="/politique-confidentialite"': 'href="/en/politique-confidentialite"',
        'href="/candidature"': 'href="/en/candidature"',
        'href="/rendez-vous"': 'href="/en/rendez-vous"',
        'href="/blog-article"': 'href="/en/blog-article"',
    }
    for fr_link, en_link in link_map.items():
        content = content.replace(fr_link, en_link)

    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    with open(dest_path, 'w', encoding='utf-8') as f:
        f.write(content)


def main():
    skip_dirs = {'app', 'en', 'node_modules', '.git', 'espace-client-4p8w1n',
                 'pirabel-admin-7x9k2m', 'api', 'Projet A', 'projet claude B'}
    skip_files = {'Projet A.html'}

    count = 0
    for root, dirs, files in os.walk(SRC):
        rel_root = os.path.relpath(root, SRC)
        if rel_root != '.' and rel_root.split(os.sep)[0] in skip_dirs:
            continue
        dirs[:] = [d for d in dirs if d not in skip_dirs]

        for f in files:
            if not f.endswith('.html') or f in skip_files:
                continue
            src_path = os.path.join(root, f)
            rel_path = os.path.relpath(src_path, SRC)
            dest_path = os.path.join(DEST, rel_path)
            translate_file(src_path, dest_path)
            count += 1

    print(f"Translated {count} files to /en/")


if __name__ == '__main__':
    main()
