#!/usr/bin/env python3
"""Catalog des 30 formations Pirabel Labs.
Source de verite pour generer toutes les pages."""

# Niveaux disponibles
LEVELS = {
    'debutant': ('Débutant', 'Beginner', '#4ade80'),
    'intermediaire': ('Intermédiaire', 'Intermediate', '#fbbf24'),
    'avance': ('Avancé', 'Advanced', '#f97316'),
    'expert': ('Expert', 'Expert', '#ef4444'),
}

# Categories
CATEGORIES = {
    'seo': ('SEO & Référencement', 'SEO & Search'),
    'web': ('Création Web', 'Web Creation'),
    'marketing': ('Marketing Digital', 'Digital Marketing'),
    'ads': ('Publicité Payante', 'Paid Advertising'),
    'social': ('Social Media', 'Social Media'),
    'content': ('Contenu & Copywriting', 'Content & Copywriting'),
    'email': ('Email Marketing', 'Email Marketing'),
    'design': ('Design & Branding', 'Design & Branding'),
    'ai': ('IA & Automatisation', 'AI & Automation'),
    'data': ('Data & Analytics', 'Data & Analytics'),
}

# Liste des 30 formations
FORMATIONS = [
    # SEO (4 formations)
    {'slug': 'seo-debutant', 'cat': 'seo', 'level': 'debutant',
     'title_fr': 'SEO pour Débutants : Maîtrisez les Fondamentaux du Référencement',
     'title_en': 'SEO for Beginners: Master the Fundamentals of Search',
     'duration_h': 12, 'lessons': 25, 'modules': 5,
     'short_fr': "Apprenez à positionner votre site sur Google de zéro, sans jargon. Mots-clés, contenu, technique, on-page, et premiers backlinks.",
     'short_en': "Learn to rank your website on Google from scratch, no jargon. Keywords, content, technical, on-page, and first backlinks."},
    {'slug': 'seo-intermediaire', 'cat': 'seo', 'level': 'intermediaire',
     'title_fr': 'SEO Intermédiaire : Audit, Optimisation et Stratégies de Croissance',
     'title_en': 'Intermediate SEO: Audit, Optimization and Growth Strategies',
     'duration_h': 18, 'lessons': 30, 'modules': 6,
     'short_fr': "Passez au niveau supérieur : audit technique complet, optimisation on-page avancée, stratégie de contenu cluster, netlinking.",
     'short_en': "Level up: complete technical audit, advanced on-page optimization, cluster content strategy, link building."},
    {'slug': 'seo-avance', 'cat': 'seo', 'level': 'avance',
     'title_fr': 'SEO Avancé : Technique, JavaScript, International et IA Générative',
     'title_en': 'Advanced SEO: Technical, JavaScript, International and Generative AI',
     'duration_h': 24, 'lessons': 32, 'modules': 7,
     'short_fr': "SEO expert : crawl & indexation, JavaScript rendering, hreflang, structured data, Core Web Vitals, SEO pour LLM.",
     'short_en': "Expert SEO: crawl & indexation, JavaScript rendering, hreflang, structured data, Core Web Vitals, SEO for LLMs."},
    {'slug': 'seo-local-google-business', 'cat': 'seo', 'level': 'intermediaire',
     'title_fr': 'SEO Local & Google Business Profile : Dominer Votre Zone',
     'title_en': 'Local SEO & Google Business Profile: Dominate Your Area',
     'duration_h': 10, 'lessons': 22, 'modules': 5,
     'short_fr': "Optimisez votre fiche Google Business, gérez vos avis, construisez vos citations locales, dominez le pack local.",
     'short_en': "Optimize your Google Business listing, manage reviews, build local citations, dominate the local pack."},

    # Création Web (4 formations)
    {'slug': 'wordpress-debutant', 'cat': 'web', 'level': 'debutant',
     'title_fr': 'WordPress pour Débutants : Créez Votre Site de A à Z',
     'title_en': 'WordPress for Beginners: Build Your Site from A to Z',
     'duration_h': 15, 'lessons': 28, 'modules': 5,
     'short_fr': "De l'achat du nom de domaine au site live : hébergement, installation, thème, plugins essentiels, premier site pro.",
     'short_en': "From domain name to live site: hosting, installation, theme, essential plugins, first pro site."},
    {'slug': 'wordpress-intermediaire', 'cat': 'web', 'level': 'intermediaire',
     'title_fr': 'WordPress Intermédiaire : Elementor, ACF, Custom Post Types',
     'title_en': 'Intermediate WordPress: Elementor, ACF, Custom Post Types',
     'duration_h': 20, 'lessons': 30, 'modules': 6,
     'short_fr': "Devenez créateur WordPress autonome : page builders avancés, ACF, CPT, child themes, performances, sécurité.",
     'short_en': "Become an autonomous WordPress creator: advanced page builders, ACF, CPT, child themes, performance, security."},
    {'slug': 'wordpress-securite-performance', 'cat': 'web', 'level': 'avance',
     'title_fr': 'WordPress Sécurité & Performance : Le Guide du Site Inviolable',
     'title_en': 'WordPress Security & Performance: The Hardened Site Guide',
     'duration_h': 12, 'lessons': 24, 'modules': 5,
     'short_fr': "Sécurisez votre WordPress contre 99% des attaques, optimisez Core Web Vitals, atteignez 95+ Lighthouse Mobile.",
     'short_en': "Secure your WordPress against 99% of attacks, optimize Core Web Vitals, hit 95+ Lighthouse Mobile."},
    {'slug': 'shopify-marchand-debutant', 'cat': 'web', 'level': 'debutant',
     'title_fr': 'Shopify pour Marchands Débutants : Lancez Votre E-commerce',
     'title_en': 'Shopify for Beginner Merchants: Launch Your E-commerce',
     'duration_h': 14, 'lessons': 26, 'modules': 5,
     'short_fr': "Boutique Shopify de zéro à premières ventes : theme, produits, paiements (Mobile Money + Stripe), livraison.",
     'short_en': "Shopify store from zero to first sales: theme, products, payments (Mobile Money + Stripe), shipping."},

    # Marketing Digital (3 formations)
    {'slug': 'marketing-digital-fondamentaux', 'cat': 'marketing', 'level': 'debutant',
     'title_fr': 'Marketing Digital : Fondamentaux Complets pour Entrepreneurs',
     'title_en': 'Digital Marketing: Complete Fundamentals for Entrepreneurs',
     'duration_h': 16, 'lessons': 28, 'modules': 6,
     'short_fr': "Compréhension globale : persona, funnel, SEO, ads, social, email, analytics. Stratégie + exécution.",
     'short_en': "Comprehensive overview: persona, funnel, SEO, ads, social, email, analytics. Strategy + execution."},
    {'slug': 'marketing-digital-strategie-avancee', 'cat': 'marketing', 'level': 'avance',
     'title_fr': 'Stratégie Marketing Digital Avancée : Frameworks et Growth',
     'title_en': 'Advanced Digital Marketing Strategy: Frameworks and Growth',
     'duration_h': 22, 'lessons': 30, 'modules': 6,
     'short_fr': "Frameworks AARRR, ICE, RICE, North Star, growth loops, brand x performance balance, attribution.",
     'short_en': "AARRR, ICE, RICE, North Star frameworks, growth loops, brand x performance balance, attribution."},
    {'slug': 'inbound-marketing-complet', 'cat': 'marketing', 'level': 'intermediaire',
     'title_fr': 'Inbound Marketing : Attirer, Convertir, Fidéliser',
     'title_en': 'Inbound Marketing: Attract, Convert, Delight',
     'duration_h': 18, 'lessons': 28, 'modules': 5,
     'short_fr': "Méthodologie HubSpot complète : aimant content, lead magnets, nurturing, marketing automation, scoring.",
     'short_en': "Complete HubSpot methodology: content magnet, lead magnets, nurturing, marketing automation, scoring."},

    # Publicité Payante (3 formations)
    {'slug': 'google-ads-debutant', 'cat': 'ads', 'level': 'debutant',
     'title_fr': 'Google Ads pour Débutants : Premier Compte Rentable',
     'title_en': 'Google Ads for Beginners: First Profitable Account',
     'duration_h': 14, 'lessons': 26, 'modules': 5,
     'short_fr': "Search, Display, YouTube, Shopping : structure compte, mots-clés, créa, budget, tracking.",
     'short_en': "Search, Display, YouTube, Shopping: account structure, keywords, creatives, budget, tracking."},
    {'slug': 'meta-ads-facebook-instagram', 'cat': 'ads', 'level': 'intermediaire',
     'title_fr': 'Meta Ads Maîtrise : Facebook + Instagram pour PME',
     'title_en': 'Meta Ads Mastery: Facebook + Instagram for SMEs',
     'duration_h': 16, 'lessons': 28, 'modules': 6,
     'short_fr': "Pixel, audiences, créas UGC, retargeting, CBO, Catalog Ads, attribution post-iOS14.",
     'short_en': "Pixel, audiences, UGC creatives, retargeting, CBO, Catalog Ads, post-iOS14 attribution."},
    {'slug': 'tiktok-ads-creator-economy', 'cat': 'ads', 'level': 'intermediaire',
     'title_fr': 'TikTok Ads & Creator Economy : Virer Sans Brûler le Budget',
     'title_en': 'TikTok Ads & Creator Economy: Go Viral Without Burning Budget',
     'duration_h': 12, 'lessons': 22, 'modules': 5,
     'short_fr': "TikTok Ads Manager, créas vidéo natives, Spark Ads, partenariats créateurs, mesure.",
     'short_en': "TikTok Ads Manager, native video creatives, Spark Ads, creator partnerships, measurement."},

    # Social Media (2 formations)
    {'slug': 'social-media-strategie-complete', 'cat': 'social', 'level': 'intermediaire',
     'title_fr': 'Stratégie Social Media Complète : 5 Plateformes Maîtrisées',
     'title_en': 'Complete Social Media Strategy: Mastering 5 Platforms',
     'duration_h': 18, 'lessons': 28, 'modules': 6,
     'short_fr': "Facebook, Instagram, TikTok, LinkedIn, X : stratégie, calendrier, créa, community, KPIs.",
     'short_en': "Facebook, Instagram, TikTok, LinkedIn, X: strategy, calendar, creatives, community, KPIs."},
    {'slug': 'linkedin-b2b-personal-branding', 'cat': 'social', 'level': 'intermediaire',
     'title_fr': 'LinkedIn B2B & Personal Branding pour Dirigeants',
     'title_en': 'LinkedIn B2B & Personal Branding for Executives',
     'duration_h': 10, 'lessons': 20, 'modules': 5,
     'short_fr': "Profil optimisé, contenu virale, inbound B2B, networking, Sales Navigator, Lead Gen Forms.",
     'short_en': "Optimized profile, viral content, B2B inbound, networking, Sales Navigator, Lead Gen Forms."},

    # Contenu & Copywriting (3 formations)
    {'slug': 'copywriting-persuasif', 'cat': 'content', 'level': 'intermediaire',
     'title_fr': 'Copywriting Persuasif : Vendre par les Mots',
     'title_en': 'Persuasive Copywriting: Sell with Words',
     'duration_h': 14, 'lessons': 26, 'modules': 5,
     'short_fr': "Frameworks AIDA, PAS, BAB, FAB. Headlines, hooks, CTAs, landing pages, emails de vente.",
     'short_en': "AIDA, PAS, BAB, FAB frameworks. Headlines, hooks, CTAs, landing pages, sales emails."},
    {'slug': 'content-marketing-strategique', 'cat': 'content', 'level': 'intermediaire',
     'title_fr': 'Content Marketing Stratégique : Du Brief à la Mesure ROI',
     'title_en': 'Strategic Content Marketing: From Brief to ROI Measurement',
     'duration_h': 16, 'lessons': 26, 'modules': 5,
     'short_fr': "Persona, piliers, calendrier, briefs, production, distribution multi-canal, mesure d'impact.",
     'short_en': "Persona, pillars, calendar, briefs, production, multi-channel distribution, impact measurement."},
    {'slug': 'redaction-seo-articles-qui-rankent', 'cat': 'content', 'level': 'debutant',
     'title_fr': 'Rédaction SEO : Écrire des Articles qui Rankent en 2026',
     'title_en': 'SEO Writing: Articles that Rank in 2026',
     'duration_h': 12, 'lessons': 24, 'modules': 5,
     'short_fr': "Recherche d'intention, structure H2/H3, optimisation on-page, longueur idéale, NLP, EEAT.",
     'short_en': "Intent research, H2/H3 structure, on-page optimization, ideal length, NLP, EEAT."},

    # Email Marketing (2 formations)
    {'slug': 'email-marketing-complet', 'cat': 'email', 'level': 'intermediaire',
     'title_fr': 'Email Marketing Complet : Délivrabilité, Segmentation, Automation',
     'title_en': 'Complete Email Marketing: Deliverability, Segmentation, Automation',
     'duration_h': 14, 'lessons': 26, 'modules': 5,
     'short_fr': "SPF/DKIM/DMARC, segmentation RFM, séquences nurturing, design email, A/B tests, KPIs.",
     'short_en': "SPF/DKIM/DMARC, RFM segmentation, nurturing sequences, email design, A/B tests, KPIs."},
    {'slug': 'newsletter-monetisation-creator', 'cat': 'email', 'level': 'intermediaire',
     'title_fr': 'Newsletter & Creator Economy : Construire une Audience Payante',
     'title_en': 'Newsletter & Creator Economy: Build a Paying Audience',
     'duration_h': 12, 'lessons': 22, 'modules': 5,
     'short_fr': "Beehiiv, Substack, ConvertKit. Growth, sponsoring, abonnements payants, communauté.",
     'short_en': "Beehiiv, Substack, ConvertKit. Growth, sponsoring, paid subscriptions, community."},

    # Design & Branding (3 formations)
    {'slug': 'branding-identite-visuelle', 'cat': 'design', 'level': 'intermediaire',
     'title_fr': 'Branding & Identité Visuelle : Bâtir une Marque Mémorable',
     'title_en': 'Branding & Visual Identity: Build a Memorable Brand',
     'duration_h': 16, 'lessons': 26, 'modules': 6,
     'short_fr': "Positionnement, naming, logo, couleurs, typographie, charte, déclinaisons multi-supports.",
     'short_en': "Positioning, naming, logo, colors, typography, guidelines, multi-format variations."},
    {'slug': 'ui-design-figma-mastery', 'cat': 'design', 'level': 'intermediaire',
     'title_fr': 'UI Design & Figma Mastery : Designer Interfaces Pro',
     'title_en': 'UI Design & Figma Mastery: Design Pro Interfaces',
     'duration_h': 20, 'lessons': 30, 'modules': 6,
     'short_fr': "Figma de A à Z : Auto Layout, components, variants, design system, prototyping, handoff dev.",
     'short_en': "Figma from A to Z: Auto Layout, components, variants, design system, prototyping, dev handoff."},
    {'slug': 'motion-design-after-effects-marketing', 'cat': 'design', 'level': 'intermediaire',
     'title_fr': 'Motion Design After Effects pour Marketing',
     'title_en': 'Motion Design After Effects for Marketing',
     'duration_h': 18, 'lessons': 28, 'modules': 5,
     'short_fr': "After Effects, animation logo, explainer videos, social videos, transitions, sound design.",
     'short_en': "After Effects, logo animation, explainer videos, social videos, transitions, sound design."},

    # IA & Automatisation (4 formations)
    {'slug': 'ia-generative-marketing', 'cat': 'ai', 'level': 'debutant',
     'title_fr': 'IA Générative pour Marketing : ChatGPT, Claude, Midjourney',
     'title_en': 'Generative AI for Marketing: ChatGPT, Claude, Midjourney',
     'duration_h': 12, 'lessons': 24, 'modules': 5,
     'short_fr': "Prompting avancé, génération contenu, visuels, voix, vidéo, workflows, productivité x10.",
     'short_en': "Advanced prompting, content generation, visuals, voice, video, workflows, productivity x10."},
    {'slug': 'agents-ia-chatbots-entreprise', 'cat': 'ai', 'level': 'avance',
     'title_fr': 'Agents IA & Chatbots Entreprise : RAG, Function Calling, Production',
     'title_en': 'Enterprise AI Agents & Chatbots: RAG, Function Calling, Production',
     'duration_h': 24, 'lessons': 32, 'modules': 7,
     'short_fr': "OpenAI API, Claude API, RAG (vector DBs), agents Make/n8n, déploiement, monitoring.",
     'short_en': "OpenAI API, Claude API, RAG (vector DBs), Make/n8n agents, deployment, monitoring."},
    {'slug': 'automatisation-make-zapier-n8n', 'cat': 'ai', 'level': 'intermediaire',
     'title_fr': 'Automatisation Make / Zapier / n8n : Workflows No-Code',
     'title_en': 'Automation Make / Zapier / n8n: No-Code Workflows',
     'duration_h': 16, 'lessons': 28, 'modules': 6,
     'short_fr': "Comparatif, cas d'usage, scénarios complexes, intégrations, erreurs courantes, scaling.",
     'short_en': "Comparison, use cases, complex scenarios, integrations, common errors, scaling."},
    {'slug': 'prompt-engineering-avance', 'cat': 'ai', 'level': 'avance',
     'title_fr': 'Prompt Engineering Avancé : Maîtriser ChatGPT, Claude, Gemini',
     'title_en': 'Advanced Prompt Engineering: Master ChatGPT, Claude, Gemini',
     'duration_h': 14, 'lessons': 24, 'modules': 5,
     'short_fr': "Few-shot, chain-of-thought, role prompting, system prompts, structured outputs, eval.",
     'short_en': "Few-shot, chain-of-thought, role prompting, system prompts, structured outputs, eval."},

    # Data & Analytics (2 formations)
    {'slug': 'ga4-google-analytics-mastery', 'cat': 'data', 'level': 'intermediaire',
     'title_fr': 'GA4 Google Analytics Mastery : Configuration et Analyse',
     'title_en': 'GA4 Google Analytics Mastery: Setup and Analysis',
     'duration_h': 14, 'lessons': 26, 'modules': 5,
     'short_fr': "Setup GA4, events, conversions, audiences, attribution, BigQuery, Looker Studio.",
     'short_en': "GA4 setup, events, conversions, audiences, attribution, BigQuery, Looker Studio."},
    {'slug': 'cro-conversion-optimization', 'cat': 'data', 'level': 'avance',
     'title_fr': 'CRO : Optimisation Taux de Conversion par les Tests',
     'title_en': 'CRO: Conversion Rate Optimization via Testing',
     'duration_h': 16, 'lessons': 26, 'modules': 5,
     'short_fr': "Hypothèses, A/B tests, VWO/Convert, heatmaps, user testing, psychologie comportementale.",
     'short_en': "Hypotheses, A/B tests, VWO/Convert, heatmaps, user testing, behavioral psychology."},
]

assert len(FORMATIONS) == 30, f"Doit avoir 30 formations, trouvé {len(FORMATIONS)}"

if __name__ == '__main__':
    print(f"Catalog : {len(FORMATIONS)} formations")
    for f in FORMATIONS:
        print(f"  - [{f['cat']:8}] [{f['level']:13}] {f['slug']} ({f['lessons']} leçons)")
